"""Seed data for PranvithDOP. Mirrors the frontend mock data so the site looks identical."""
import uuid

# Asset hero images (uploaded by user)
IMG_CREATIVE_LUT = "/assets/creative-luts.png"
IMG_SOUND_FX = "/assets/cinematic-sound-fx.png"


def _landing(headline, subhead, bullets, before_after_desc, compat, table, faqs):
    return {
        "hero": {
            "headline": headline,
            "subhead": subhead,
        },
        "features": bullets,
        "compatibility": compat,
        "before_after": before_after_desc,
        "market_table": table,
        "faqs": faqs,
    }


def _thanks(title, message, instructions):
    return {
        "title": title,
        "message": message,
        "instructions": instructions,
    }


COURSES = [
    {
        "id": str(uuid.uuid4()),
        "title": "PREMIERE Pro BEGINNER TO EXPORT",
        "description": "Premiere Pro Mastery \u2014 From Beginner to Export! The Ultimate Premiere Pro Course \u2014 Learn. Edit. Create. Export. Do you want to master Adobe Premiere Pro from scratch and turn your ideas into professional-level videos?",
        "lectures": 42,
        "discount": "70% OFF",
        "price": 2999,
        "original": 9999,
        "image": "",
        "tag": "Premiere Pro",
        "color": "from-purple-600 to-indigo-700",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Family Forever with AI",
        "description": "Create stunning wedding and family memories using AI-powered editing techniques. Master the art of cinematic storytelling with modern AI tools and workflows.",
        "lectures": 7,
        "discount": "85% OFF",
        "price": 1500,
        "original": 9999,
        "image": "",
        "tag": "AI Editing",
        "color": "from-amber-500 to-orange-600",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "After Effects",
        "description": "Master After Effects from scratch and turn your ideas into professional-level videos. This course is perfect for beginners who want to learn motion graphics, VFX, and editing.",
        "lectures": 35,
        "discount": "COMPLETE COURSE",
        "price": 2999,
        "original": None,
        "image": "",
        "tag": "After Effects",
        "color": "from-violet-600 to-purple-700",
    },
]

TESTIMONIALS = [
    {"id": str(uuid.uuid4()), "name": "Priya Sharma", "role": "YouTuber", "text": "Best investment I made for my channel. The techniques are industry-standard.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Arun Patel", "role": "Freelancer", "text": "From zero to landing my first client. Pranavith explains everything so cleanly.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Sneha Reddy", "role": "Student", "text": "Booked my first wedding edit project within weeks of completing it.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Vikram Singh", "role": "Wedding Editor", "text": "The AI editing module alone was worth the price. My clients love the results!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Meera Krishnan", "role": "Instagram Creator", "text": "My reels quality improved drastically. Gained 50K followers in 2 months!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Karthik Nair", "role": "Brand Manager", "text": "We do all our brand videos in-house. No more outsourcing needed.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Rohit Verma", "role": "Vlogger", "text": "The color grading section was mind-blowing. My videos look cinematic now.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Lakshmi Pillai", "role": "Entrepreneur", "text": "Started my own editing service after this course. Already have 10+ clients!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Siddharth Rao", "role": "Music Producer", "text": "Perfect for creating music videos. The effects tutorials are incredible.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Pooja Desai", "role": "Travel Blogger", "text": "My travel videos went viral after applying these techniques. Thank you!", "rating": 5},
]

FAQS = [
    {
        "id": str(uuid.uuid4()),
        "q": "I can find free tutorials on YouTube. Why should I pay to join PranvithDOP?",
        "a": "YouTube tutorials are scattered and lack structure. PranvithDOP provides a step-by-step roadmap, real projects, lifetime access, downloadable assets, community support, and direct mentorship from a professional editor \u2014 saving you months of trial and error.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Is this course for absolute beginners, or do I need prior experience?",
        "a": "No prior experience required! We start from the absolute basics \u2014 installing software, understanding the interface \u2014 and gradually take you to advanced professional techniques.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Who is this course NOT for?",
        "a": "This course is not for people looking for quick shortcuts without practice. If you are not willing to spend time editing and applying what you learn, this is not for you.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "I have a full-time job/college. How much time do I need to dedicate daily?",
        "a": "Just 30\u201360 minutes a day is enough. The course is self-paced, so you can learn whenever you have free time \u2014 early mornings, lunch breaks, or weekends.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Will I just be watching videos, or will I actually edit?",
        "a": "You will be editing real projects! Every module comes with practice files, assignments, and challenges that mirror real-world client work.",
    },
]

PAGES = [
    {
        "id": str(uuid.uuid4()),
        "slug": "home",
        "title": "Home",
        "sections": {
            "hero": {
                "headline": "Video Editing Mastery for Creators",
                "subheadline": "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.",
                "buttonText": "Explore Assets",
                "buttonUrl": "/assets",
                "image": "",
            },
        },
        "seo_title": "PranvithDOP \u2014 Video Editing Courses and Assets",
        "seo_description": "Premium video editing training, LUT packs, templates, and workflow resources for creators.",
        "published": True,
        "created_at": "2025-12-01T00:00:00Z",
        "updated_at": None,
    },
]

CMS_PAGES = [
    {
        "id": str(uuid.uuid4()),
        "page_key": "home",
        "title": "Home",
        "subtitle": "Premium video editing training, assets, showreels, and production services.",
        "slug": "home",
        "path": "/",
        "status": "published",
        "seo_title": "PranvithDOP - Video Editing Courses and Assets",
        "seo_description": "Premium video editing training, LUT packs, templates, and workflow resources for creators.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "courses",
        "title": "Courses",
        "subtitle": "Practical cinematic editing lessons and student outcomes.",
        "slug": "courses",
        "path": "/courses",
        "status": "published",
        "seo_title": "Courses - PranvithDOP",
        "seo_description": "Learn practical editing workflows, storytelling, color, sound, and delivery systems.",
        "settings": {"courses_enabled": False, "show_coming_soon": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "about",
        "title": "About",
        "subtitle": "DOP, filmmaker, editor, drone pilot, and visual storyteller.",
        "slug": "about",
        "path": "/about",
        "status": "published",
        "seo_title": "About - PranvithDOP",
        "seo_description": "About PranvithDOP cinematography, editing, drone, DI, and commercial visual work.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "assets",
        "title": "Assets",
        "subtitle": "Premium LUTs, sound packs, motion templates and more built for editors.",
        "slug": "assets",
        "path": "/assets",
        "status": "published",
        "seo_title": "Creative Assets - PranvithDOP",
        "seo_description": "Browse PranvithDOP digital assets for video editors and creators.",
        "settings": {"show_product_listing": True, "show_filters": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "works",
        "title": "Our Works",
        "subtitle": "A curated portfolio of cinematography, drone work, product visuals, and post-production.",
        "slug": "works",
        "path": "/works",
        "status": "published",
        "seo_title": "Our Works - PranvithDOP",
        "seo_description": "Explore PranvithDOP commercial, wedding, drone, product, film, and editing work.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "hire",
        "title": "Hire From Us",
        "subtitle": "Build a film, campaign, or visual story with cinematic intent.",
        "slug": "hire",
        "path": "/hire",
        "status": "published",
        "seo_title": "Hire PranvithDOP",
        "seo_description": "Send a project enquiry for cinematic shoots, brand films, wedding films, drone work, and edits.",
        "settings": {"show_enquiry_form": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
]


def _cms_section(page_key, section_id, section_type, title="", subtitle="", description="", button_text="", button_link="", media_type="auto", media_url="", poster_url="", data=None, enabled=True, sort_order=0):
    return {
        "id": str(uuid.uuid4()),
        "section_id": section_id,
        "page_key": page_key,
        "type": section_type,
        "title": title,
        "subtitle": subtitle,
        "description": description,
        "button_text": button_text,
        "button_link": button_link,
        "media_type": media_type,
        "media_url": media_url,
        "poster_url": poster_url,
        "data": data or {},
        "enabled": enabled,
        "sort_order": sort_order,
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    }


CMS_SECTIONS = [
    _cms_section("home", "hero", "hero", "Video Editing Mastery for Creators", "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.", "Master the art of video editing with comprehensive courses, creative assets, showreels, and production services.", "Explore Assets", "/assets", sort_order=0, data={"secondary_button_text": "Book a Project", "secondary_button_link": "/hire"}),
    _cms_section("home", "services", "services_cards", "Services", "Cinematic production and post-production support.", data={"items": [
        {"title": "Video Editing", "description": "Clean story edits, reels, ads, and long-form content.", "enabled": True},
        {"title": "Cinematography", "description": "DOP-led planning for light, movement, and visual tone.", "enabled": True},
        {"title": "Drone Visuals", "description": "Aerial sequences for events, places, campaigns, and films.", "enabled": True},
    ]}, sort_order=1),
    _cms_section("home", "showreel", "showreel", "Featured Showreel", "A cinematic portfolio of light, movement, and emotion.", "Commercials, wedding stories, drone sequences, product frames, and post-production work shaped for premium digital delivery.", sort_order=2),
    _cms_section("home", "cta", "cta", "Ready to create cinematic visuals?", "", "Explore assets, courses, showreels, and production services built for serious creators.", "Book a Project", "/hire", sort_order=3),
    _cms_section("courses", "coming-soon", "cta", "Courses Coming Soon", "We are preparing premium video editing courses. Stay tuned.", "", "Explore Assets", "/assets", sort_order=0),
    _cms_section("courses", "what-youll-learn", "course_showcase", "What You'll Learn", "Skills that turn timelines into stories.", data={"items": [
        {"title": "Premiere Pro Workflow", "description": "Build clean timelines, organize footage, cut faster, and export professionally.", "enabled": True},
        {"title": "After Effects Motion", "description": "Create titles, motion graphics, transitions, and polished visual effects.", "enabled": True},
        {"title": "AI Editing Tools", "description": "Use modern AI tools to speed up captions, cleanup, reframing, and creative workflows.", "enabled": True},
    ]}, sort_order=1),
    _cms_section("courses", "faq", "faq", "FAQ", "", data={"items": [
        {"question": "Do I need prior editing experience?", "answer": "No. The course content is beginner-friendly and moves into practical professional workflows.", "enabled": True},
    ]}, sort_order=2),
    _cms_section("about", "hero", "image_text", "DOP, filmmaker, editor, drone pilot, and visual storyteller.", "About Pranvith Dop", "PranvithDOP creates cinematic visuals for brands, creators, weddings, products, and digital campaigns.", "Book a project", "/hire", "image", "/assets/brand-profile.png", sort_order=0),
    _cms_section("about", "stats", "services_cards", "Creative Highlights", "", data={"items": [
        {"title": "250+", "description": "Film, ad & edit projects", "enabled": True},
        {"title": "80+", "description": "Product and commercial shoots", "enabled": True},
        {"title": "120+", "description": "Aerial/drone sequences", "enabled": True},
        {"title": "3,000+", "description": "Post-production hours", "enabled": True},
    ]}, sort_order=1),
    _cms_section("assets", "hero", "hero", "Creative Assets Store", "Premium LUTs, sound packs, motion templates and more - built for editors.", "", "", "", sort_order=0),
    _cms_section("works", "hero", "hero", "Films, commercials, aerials, and edits crafted for impact.", "PORTFOLIO", "A curated portfolio of PranvithDOP cinematography, drone work, product visuals, and post-production projects.", sort_order=0),
    _cms_section("works", "showreel", "showreel", "A cinematic portfolio of light, movement, and emotion.", "FEATURED SHOWREEL", "Commercials, wedding stories, drone sequences, product frames, and post-production work shaped for premium digital delivery.", "View all works", "/works", sort_order=1),
    _cms_section("works", "projects", "portfolio_grid", "Portfolio Projects", "", data={"items": []}, sort_order=2),
    _cms_section("hire", "hero", "hero", "Build a film, campaign, or visual story with cinematic intent.", "Book PranvithDOP", "Tell us about your shoot, brand film, wedding, reel, product campaign, or edit. We will shape the look, schedule, and creative plan around the story you want people to feel.", sort_order=0),
    _cms_section("hire", "services", "services_cards", "What We Can Build", "", data={"items": [
        {"title": "Plan the shoot", "description": "Share your date, location, budget, and visual references.", "enabled": True},
        {"title": "Shoot anywhere", "description": "Available for local, destination, commercial, and drone projects.", "enabled": True},
    ]}, sort_order=1),
    _cms_section("hire", "enquiry-form", "contact_form", "Start a project enquiry", "", "A few details are enough. We will follow up with the right next step.", "Send Project Enquiry", "/hire", sort_order=2),
]

# ---------- 8 ASSETS WITH FULL CMS CONTENT ----------
_COMPAT_VIDEO = ["Adobe Premiere Pro", "DaVinci Resolve", "Final Cut Pro", "After Effects"]
_COMPAT_AUDIO = ["Premiere Pro", "Final Cut Pro", "DaVinci Resolve", "Logic Pro"]
_COMPAT_FONTS = ["After Effects", "Premiere Pro", "Photoshop", "Illustrator"]

ASSET_PRODUCTS = [
    {
        "id": str(uuid.uuid4()),
        "slug": "creative-lut-pack",
        "name": "Creative LUT Pack",
        "category": "LUT Pack",
        "price": 49,
        "sale_price": 49,
        "is_free": False,
        "description": "Pranvith Creative LUT Pack \u2014 a curated set of cinematic 3D LUTs for film-quality color grades in one click.",
        "features": [
            "10+ cinematic 3D LUTs",
            "One-click professional grading",
            "Works with LOG, RAW & standard footage",
            "Beginner-friendly install guide",
            "Lifetime updates",
            "Compatible with major editing software",
        ],
        "benefits": ["Save grading time", "Premium cinematic look", "Client-ready in minutes"],
        "faqs": [
            {"q": "Which apps work with this pack?", "a": "Premiere Pro, DaVinci Resolve, Final Cut Pro, After Effects and any editor that supports 3D LUT imports."},
            {"q": "Do I need advanced editing skills?", "a": "No. The LUTs are drag-and-drop. A simple import is all you need."},
            {"q": "How do I receive the files?", "a": "After payment you\u2019re redirected to a dedicated thank-you page with the instant download link and install instructions."},
            {"q": "Do I get updates?", "a": "Yes. Future updates are included with your purchase."},
        ],
        "images": [IMG_CREATIVE_LUT],
        "hero_image": IMG_CREATIVE_LUT,
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/creative-lut-pack.zip",
        "payment_link": "https://rzp.io/rzp/yThuB5K",
        "landing_content": _landing(
            "Pranvith Creative LUT Pack",
            "Give your videos the cinematic grade used by professional filmmakers.",
            [
                "Professional Cinematic Look",
                "Works Instantly",
                "Saves Editing Time",
                "Beginner Friendly",
                "Professional Color Science",
                "Compatible with major editors",
            ],
            "Flat, ungraded footage versus a film-grade cinematic finish with depth and contrast.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b949 one-time", "\u20b9499+"],
                ["Support", "Direct email support", "Limited or none"],
                ["Ease of Use", "One-click install", "Manual setup"],
                ["Quality", "Cinematic color science", "Generic grades"],
                ["Updates", "Included with purchase", "Extra charge"],
            ],
            [
                {"q": "Can I use these LUTs with any editing software?", "a": "Yes \u2014 Premiere Pro, DaVinci Resolve, Final Cut Pro, After Effects and any 3D-LUT-capable editor."},
                {"q": "Will the LUTs work with my footage?", "a": "Yes. Calibrated for RAW, LOG and standard formats."},
                {"q": "Will I get updates?", "a": "Yes \u2014 included with your purchase."},
            ],
        ),
        "thank_you_content": _thanks(
            "Thank you for your purchase!",
            "Your Pranvith Creative LUT Pack is ready. Use the download button below to grab the .zip file.",
            [
                "Unzip the downloaded archive on your computer.",
                "Open your editor (Premiere Pro / DaVinci / Final Cut).",
                "Import the LUT files via your color panel.",
                "Apply the LUT and adjust intensity to taste.",
            ],
        ),
        "seo_title": "Creative LUT Pack \u2014 PranvithDOP",
        "seo_description": "Premium cinematic 3D LUTs for one-click professional color grading.",
        "published": True,
        "created_at": "2025-12-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/creative-lut-pack",
        "sold_count": 12,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "premiere-pro-wedding-templates",
        "name": "Premiere Pro Wedding Templates",
        "category": "Templates",
        "price": 299,
        "sale_price": 299,
        "is_free": False,
        "description": "Animated Premiere Pro templates engineered for cinematic wedding edits \u2014 invitations, openers, lower thirds and more.",
        "features": [
            "10+ ready-to-use wedding templates",
            "Drag-and-drop in Premiere Pro",
            "Editable text & color",
            "4K resolution",
            "Cinematic typography",
            "Free updates",
        ],
        "benefits": ["Save hours of design", "Premium wedding aesthetic", "Easy client customisation"],
        "faqs": [
            {"q": "Which Premiere Pro version is required?", "a": "Premiere Pro CC 2020 or later."},
            {"q": "Can I customise text and music?", "a": "Yes \u2014 every layer is fully editable."},
            {"q": "Are these for commercial use?", "a": "Yes, you can use them in client wedding deliverables."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/premiere-pro-wedding-templates.zip",
        "payment_link": "https://rzp.io/rzp/ol7TMWt",
        "landing_content": _landing(
            "Premiere Pro Wedding Templates",
            "Cinematic wedding edits in a fraction of the time.",
            [
                "Wedding invitations",
                "Animated openers",
                "Lower thirds",
                "Save-the-date templates",
                "Modern film aesthetic",
                "4K resolution",
            ],
            "Plain wedding edits vs. cinematic, story-driven sequences with elegant typography.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b9299 one-time", "\u20b91499+"],
                ["Format", "Editable .prproj", "Locked exports"],
                ["Customisation", "Full text/colour", "Limited"],
                ["Updates", "Included", "Extra charge"],
            ],
            [
                {"q": "Do I need any plugins?", "a": "No \u2014 templates run on stock Premiere Pro."},
                {"q": "Can I export in any resolution?", "a": "Yes, the project is 4K and exports to any common spec."},
            ],
        ),
        "thank_you_content": _thanks(
            "Welcome to the Wedding Template family!",
            "Your Premiere Pro Wedding Templates are ready. Download below and follow the install guide.",
            [
                "Unzip the project files.",
                "Open the .prproj inside Premiere Pro.",
                "Replace the placeholder text with your details.",
                "Render at your delivery resolution.",
            ],
        ),
        "seo_title": "Premiere Pro Wedding Templates \u2014 PranvithDOP",
        "seo_description": "Cinematic, fully editable Premiere Pro templates for wedding editors.",
        "published": True,
        "created_at": "2025-11-15T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/premiere-pro-wedding-templates",
        "sold_count": 24,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "cinematic-sound-fx-pack",
        "name": "Cinematic Sound FX Pack",
        "category": "Sound FX",
        "price": 149,
        "sale_price": 149,
        "is_free": False,
        "description": "A curated set of cinematic impacts, risers, whooshes and atmospheres for premium video edits.",
        "features": [
            "100+ cinematic SFX",
            "Impacts, risers, whooshes",
            "Royalty-free for client work",
            "High-quality 24-bit WAV",
            "Organised by category",
            "Drag-and-drop ready",
        ],
        "benefits": ["Boost production value", "Faster sound design", "Pro-level cinematic feel"],
        "faqs": [
            {"q": "Are these royalty-free?", "a": "Yes, royalty-free for personal and client projects."},
            {"q": "What format are the files?", "a": "High-quality 24-bit WAV."},
        ],
        "images": [IMG_SOUND_FX],
        "hero_image": IMG_SOUND_FX,
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/cinematic-sound-fx-pack.zip",
        "payment_link": "https://rzp.io/rzp/2XRdX6KE",
        "landing_content": _landing(
            "Cinematic Sound FX Pack",
            "Premium cinematic sound design for editors who want production-grade impact.",
            [
                "100+ cinematic SFX",
                "Impacts & risers",
                "Whooshes & transitions",
                "Atmospheres & drones",
                "Royalty-free",
                "Organised library",
            ],
            "Edits that feel flat vs. immersive, cinematic moments driven by tasteful sound design.",
            _COMPAT_AUDIO,
            [
                ["Price", "\u20b9149 one-time", "\u20b9999+"],
                ["Format", "24-bit WAV", "Compressed MP3"],
                ["Royalty", "Free for clients", "Subscription only"],
            ],
            [
                {"q": "Will this work on a Mac?", "a": "Yes \u2014 WAV files work on all major platforms."},
                {"q": "Is there a music license?", "a": "These are sound effects \u2014 royalty-free for editing use."},
            ],
        ),
        "thank_you_content": _thanks(
            "Sound design unlocked!",
            "Your Cinematic Sound FX Pack is ready to download.",
            [
                "Unzip the archive.",
                "Place the folder in your sound library.",
                "Drag the WAVs onto your timeline.",
                "Mix to taste.",
            ],
        ),
        "seo_title": "Cinematic Sound FX Pack \u2014 PranvithDOP",
        "seo_description": "Premium 24-bit WAV cinematic sound effects, royalty-free for editing projects.",
        "published": True,
        "created_at": "2025-11-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/cinematic-sound-fx-pack",
        "sold_count": 8,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "after-effects-title-templates",
        "name": "After Effects Title Templates",
        "category": "Templates",
        "price": 199,
        "sale_price": 199,
        "is_free": False,
        "description": "Animated title templates and lower thirds for After Effects \u2014 cinematic, editable and ready to drop in.",
        "features": [
            "20+ animated titles",
            "Lower thirds included",
            "Editable text & colour",
            "AE 2020+ compatible",
            "4K resolution",
            "Lifetime updates",
        ],
        "benefits": ["Save design time", "Cinematic typography", "Story-friendly motion"],
        "faqs": [
            {"q": "Which After Effects version is required?", "a": "After Effects CC 2020 or later."},
            {"q": "Can I edit colours and fonts?", "a": "Yes, fully editable."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/after-effects-title-templates.zip",
        "payment_link": "https://rzp.io/rzp/8eKZEb7v",
        "landing_content": _landing(
            "After Effects Title Templates",
            "Drop-in cinematic titles and lower thirds that elevate any edit.",
            [
                "20+ animated titles",
                "Lower thirds",
                "Editable text & colour",
                "AE 2020+ compatible",
                "Modular structure",
                "Lifetime updates",
            ],
            "Edits with static titles vs. dynamic, story-driven motion typography.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b9199 one-time", "\u20b91499+"],
                ["Editability", "Full text/colour", "Limited"],
                ["Resolution", "4K", "1080p"],
            ],
            [
                {"q": "Does this work in Premiere Pro?", "a": "Designed for AE \u2014 you can export and use the result in Premiere Pro."},
                {"q": "Do I need plugins?", "a": "No additional plugins required."},
            ],
        ),
        "thank_you_content": _thanks(
            "Titles unlocked!",
            "Your After Effects Title Templates are ready.",
            [
                "Unzip the archive.",
                "Open the .aep project in After Effects.",
                "Edit the text & colour in the comp panel.",
                "Render and import into your edit.",
            ],
        ),
        "seo_title": "After Effects Title Templates \u2014 PranvithDOP",
        "seo_description": "Cinematic animated title templates and lower thirds for After Effects.",
        "published": True,
        "created_at": "2025-10-20T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/after-effects-title-templates",
        "sold_count": 18,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "royalty-free-music-bundle",
        "name": "Royalty-Free Music Bundle",
        "category": "Music",
        "price": 249,
        "sale_price": 249,
        "is_free": False,
        "description": "A bundle of cinematic, upbeat and emotional royalty-free tracks for editors and creators.",
        "features": [
            "30+ original tracks",
            "Cinematic, upbeat & emotional moods",
            "Multiple track lengths",
            "Royalty-free for client work",
            "High-quality WAV & MP3",
            "Lifetime updates",
        ],
        "benefits": ["Faster scoring", "No copyright strikes", "Premium production"],
        "faqs": [
            {"q": "Can I use these in client work?", "a": "Yes \u2014 fully royalty-free."},
            {"q": "What formats are included?", "a": "High-quality WAV and MP3."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/royalty-free-music-bundle.zip",
        "payment_link": "https://rzp.io/rzp/GmCfBooE",
        "landing_content": _landing(
            "Royalty-Free Music Bundle",
            "Cinematic, upbeat and emotional tracks to score any edit.",
            [
                "30+ tracks",
                "Cinematic moods",
                "Upbeat tracks",
                "Emotional pieces",
                "Royalty-free",
                "Lifetime updates",
            ],
            "Edits scored with stock loops vs. compositions that feel handcrafted for the story.",
            _COMPAT_AUDIO,
            [
                ["Price", "\u20b9249 one-time", "\u20b91299+"],
                ["License", "Royalty-free", "Subscription"],
                ["Track count", "30+", "10\u201320"],
            ],
            [
                {"q": "Do I need to credit Pranvith?", "a": "Crediting is appreciated but not required."},
                {"q": "Can I use these on YouTube?", "a": "Yes \u2014 royalty-free for streaming platforms."},
            ],
        ),
        "thank_you_content": _thanks(
            "Music bundle unlocked!",
            "Your Royalty-Free Music Bundle is ready.",
            [
                "Unzip the archive.",
                "Browse the tracks by mood folder.",
                "Drag the file into your edit.",
                "Mix to your scene.",
            ],
        ),
        "seo_title": "Royalty-Free Music Bundle \u2014 PranvithDOP",
        "seo_description": "Premium royalty-free music for editors \u2014 cinematic, upbeat and emotional tracks.",
        "published": True,
        "created_at": "2025-10-10T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/royalty-free-music-bundle",
        "sold_count": 25,
    },
    # ---------- FREE assets ----------
    {
        "id": str(uuid.uuid4()),
        "slug": "smooth-transitions-pack",
        "name": "Smooth Transitions Pack",
        "category": "Transitions",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free pack of modern transitions for reels, YouTube videos, and short-form content.",
        "features": [
            "20+ smooth transitions",
            "Camera moves",
            "Zoom & spin transitions",
            "Drag-and-drop ready",
            "Compatible with major editors",
            "Free forever",
        ],
        "benefits": ["Faster editing", "Smooth visual flow", "Reels-ready polish"],
        "faqs": [
            {"q": "Are these really free?", "a": "Yes \u2014 100% free."},
            {"q": "Can I use these commercially?", "a": "Yes, for personal and client projects."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/smooth-transitions-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Smooth Transitions Pack",
            "Modern transitions to make every cut feel intentional.",
            [
                "20+ transitions",
                "Camera moves",
                "Zoom transitions",
                "Spin & whip",
                "Drag-and-drop",
                "Free forever",
            ],
            "Hard cuts that feel jarring vs. smooth movement that pulls the viewer forward.",
            _COMPAT_VIDEO,
            [
                ["Price", "FREE", "\u20b9499+"],
                ["Use", "Personal & client", "Personal only"],
            ],
            [
                {"q": "How do I install?", "a": "Drag the .mogrt files into your editor and drop onto your timeline."},
                {"q": "Will this work on M-series Macs?", "a": "Yes."},
            ],
        ),
        "thank_you_content": _thanks(
            "Transitions unlocked!",
            "Your Smooth Transitions Pack is ready.",
            [
                "Click Download below.",
                "Unzip the archive.",
                "Drop the transitions on your timeline.",
                "Adjust the duration to your cut.",
            ],
        ),
        "seo_title": "Smooth Transitions Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "Free pack of modern transitions for reels and short-form video editors.",
        "published": True,
        "created_at": "2025-09-15T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/smooth-transitions-pack",
        "sold_count": 0,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "color-gradients-pack",
        "name": "Color Gradients Pack",
        "category": "Gradients",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free set of premium color gradients for designers, editors and motion artists.",
        "features": [
            "50+ gradients",
            "Hand-crafted palettes",
            "Use in After Effects, Premiere & Photoshop",
            "PNG + .grd format",
            "Free for commercial use",
            "Updates included",
        ],
        "benefits": ["Faster design", "Modern aesthetic", "Premium colour stories"],
        "faqs": [
            {"q": "Where can I use these gradients?", "a": "Any design or video tool that accepts gradient swatches or PNGs."},
            {"q": "Is this free for commercial use?", "a": "Yes."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/color-gradients-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Color Gradients Pack",
            "Premium gradient palettes for designers, editors and motion artists.",
            [
                "50+ gradients",
                "Hand-crafted palettes",
                "PNG + .grd",
                "Photoshop swatches",
                "Free commercial use",
                "Updates included",
            ],
            "Edits that feel flat vs. modern, gradient-driven palettes that carry the brand.",
            ["Premiere Pro", "After Effects", "Photoshop", "Figma"],
            [
                ["Price", "FREE", "\u20b9299+"],
                ["License", "Commercial OK", "Personal only"],
            ],
            [
                {"q": "How do I import the gradients?", "a": "Load the .grd in Photoshop, or use the PNGs as overlays."},
                {"q": "Can I tweak the colours?", "a": "Yes \u2014 every gradient is editable."},
            ],
        ),
        "thank_you_content": _thanks(
            "Gradients unlocked!",
            "Your Color Gradients Pack is ready.",
            [
                "Unzip the archive.",
                "Open the .grd file in Photoshop to load swatches.",
                "Use the PNG overlays directly in your editor.",
            ],
        ),
        "seo_title": "Color Gradients Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "Free premium gradients for designers, editors and motion artists.",
        "published": True,
        "created_at": "2025-09-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/color-gradients-pack",
        "sold_count": 0,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "typography-fonts-pack",
        "name": "Typography Fonts Pack",
        "category": "Fonts",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free typography pack with 80+ premium fonts and title styles for video editors.",
        "features": [
            "80+ premium fonts",
            "Modern & cinematic styles",
            "Free for commercial use",
            "Easy install",
            "Works in Photoshop, AE & Premiere",
            "Lifetime updates",
        ],
        "benefits": ["Better titles", "Faster design", "Professional branding"],
        "faqs": [
            {"q": "Are these free for commercial use?", "a": "Yes, all fonts in this bundle are licensed for commercial work."},
            {"q": "How do I install them?", "a": "Double-click each font file and click \u201cInstall\u201d on Mac or Windows."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/typography-fonts-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Typography Fonts Pack",
            "80+ free premium fonts to design titles, lower thirds, posters and reels.",
            [
                "80+ premium fonts",
                "Modern styles",
                "Cinematic display fonts",
                "Free commercial use",
                "Cross-platform",
                "Lifetime updates",
            ],
            "Default system fonts vs. cinematic typography that feels designed.",
            _COMPAT_FONTS,
            [
                ["Price", "FREE", "\u20b9999+"],
                ["License", "Commercial OK", "Personal only"],
                ["Font count", "80+", "10\u201320"],
            ],
            [
                {"q": "Will these work on Final Cut Pro?", "a": "Yes \u2014 once installed they appear in every app."},
                {"q": "How do I install?", "a": "Double-click each .ttf/.otf and click Install."},
            ],
        ),
        "thank_you_content": _thanks(
            "Fonts unlocked!",
            "Your Typography Fonts Pack is ready.",
            [
                "Unzip the archive.",
                "Double-click each font file.",
                "Click \u201cInstall\u201d (Mac/Windows).",
                "Use the fonts in your editor of choice.",
            ],
        ),
        "seo_title": "Typography Fonts Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "80+ free premium fonts for editors, designers and motion artists.",
        "published": True,
        "created_at": "2025-08-20T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/typography-fonts-pack",
        "sold_count": 0,
    },
]

BLOG_CATEGORIES = [
    {"id": str(uuid.uuid4()), "name": "Editing Tips", "slug": "editing-tips"},
    {"id": str(uuid.uuid4()), "name": "Workflow", "slug": "workflow"},
]

BLOG_POSTS = [
    {
        "id": str(uuid.uuid4()),
        "title": "5 Pro Editing Tricks for Premiere Pro",
        "slug": "5-pro-editing-tricks-for-premiere-pro",
        "category": "editing-tips",
        "tags": ["premiere-pro", "editing", "tips"],
        "excerpt": "Boost your Premiere Pro workflow with five pro editing tricks that save time and improve your final video.",
        "content": "Learn fast cuts, color grading shortcuts, audio cleanup, motion graphics tips, and export settings for better results.",
        "featured_image": "",
        "seo_title": "5 Pro Editing Tricks for Premiere Pro",
        "seo_description": "Discover key Premiere Pro tricks for faster workflows and better video quality.",
        "published": True,
        "created_at": "2025-11-15T00:00:00Z",
        "updated_at": None,
    },
]

SETTINGS = {
    "site_name": "PranvithDOP",
    "theme": "dark",
    "notifications_enabled": True,
    "site_description": "Premium video editing training, LUT assets, courses and editorial services.",
    "contact_email": "info@pranvithdop.com",
    "contact_phone": "+91 9059867883",
    "contact_address": "Hyderabad, India",
    "home_hero": {
        "badge_text": "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.",
        "hero_title": "Video Editing Mastery for Creators",
        "hero_subtitle": "Master the art of video editing with our comprehensive courses. From beginner basics to advanced techniques, learn professional editing skills that transform your creative vision into stunning reality.",
        "primary_button_text": "Explore Assets",
        "primary_button_link": "/assets",
        "secondary_button_text": "Join Community",
        "secondary_button_link": "/courses",
        "hero_media_type": "auto",
        "hero_media_url": "",
        "hero_media_poster_url": "",
        "hero_media_autoplay": True,
        "hero_media_muted": True,
        "hero_media_loop": True,
    },
    "instagram_profile": {
        "username": "pranvith_dop",
        "display_name": "Pranvith Dop",
        "profile_image_url": "/assets/brand-profile.png",
        "followers_count": "5,131",
        "following_count": "10",
        "posts_count": "",
        "bio_line_1": "🎥 DOP | Filmmaker | Video Editor",
        "bio_line_2": "🚁 Drone Pilot | DI",
        "bio_line_3": "📸 Product & Commercial Photography",
        "bio_line_4": "🎨 Graphic Design",
        "link_text": "youtube.com/@pranvithdop",
        "link_url": "https://www.youtube.com/@pranvithdop",
        "follow_button_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
        "cards": [
            {"title": "Cinematic editing reel", "type": "Reel", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 0},
            {"title": "Behind the scenes", "type": "Post", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 1},
            {"title": "Drone shot preview", "type": "Video", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 2},
            {"title": "Commercial frame", "type": "Reel", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 3},
            {"title": "DI color grade", "type": "Post", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 4},
            {"title": "Graphic design post", "type": "Video", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 5},
        ],
    },
}

