"""Seed data for PranvithDOP. Mirrors the frontend mock data so the site looks identical."""
import uuid

# Asset hero images (uploaded by user)
IMG_CREATIVE_LUT = "/assets/creative-luts.png"
IMG_SOUND_FX = "/assets/cinematic-sound-fx.png"


def _landing(headline, subhead, bullets, before_after_desc, compat, table, faqs):
    return {
        "hero": {
            "headline": headline,
            "subhead": subhead,
        },
        "features": bullets,
        "compatibility": compat,
        "before_after": before_after_desc,
        "market_table": table,
        "faqs": faqs,
    }


def _thanks(title, message, instructions):
    return {
        "title": title,
        "message": message,
        "instructions": instructions,
    }


COURSES = [
    {
        "id": str(uuid.uuid4()),
        "title": "PREMIERE Pro BEGINNER TO EXPORT",
        "description": "Premiere Pro Mastery \u2014 From Beginner to Export! The Ultimate Premiere Pro Course \u2014 Learn. Edit. Create. Export. Do you want to master Adobe Premiere Pro from scratch and turn your ideas into professional-level videos?",
        "lectures": 42,
        "discount": "70% OFF",
        "price": 2999,
        "original": 9999,
        "image": "",
        "tag": "Premiere Pro",
        "color": "from-purple-600 to-indigo-700",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Family Forever with AI",
        "description": "Create stunning wedding and family memories using AI-powered editing techniques. Master the art of cinematic storytelling with modern AI tools and workflows.",
        "lectures": 7,
        "discount": "85% OFF",
        "price": 1500,
        "original": 9999,
        "image": "",
        "tag": "AI Editing",
        "color": "from-amber-500 to-orange-600",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "After Effects",
        "description": "Master After Effects from scratch and turn your ideas into professional-level videos. This course is perfect for beginners who want to learn motion graphics, VFX, and editing.",
        "lectures": 35,
        "discount": "COMPLETE COURSE",
        "price": 2999,
        "original": None,
        "image": "",
        "tag": "After Effects",
        "color": "from-violet-600 to-purple-700",
    },
]

TESTIMONIALS = [
    {"id": str(uuid.uuid4()), "name": "Priya Sharma", "role": "YouTuber", "text": "Best investment I made for my channel. The techniques are industry-standard.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Arun Patel", "role": "Freelancer", "text": "From zero to landing my first client. Pranavith explains everything so cleanly.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Sneha Reddy", "role": "Student", "text": "Booked my first wedding edit project within weeks of completing it.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Vikram Singh", "role": "Wedding Editor", "text": "The AI editing module alone was worth the price. My clients love the results!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Meera Krishnan", "role": "Instagram Creator", "text": "My reels quality improved drastically. Gained 50K followers in 2 months!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Karthik Nair", "role": "Brand Manager", "text": "We do all our brand videos in-house. No more outsourcing needed.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Rohit Verma", "role": "Vlogger", "text": "The color grading section was mind-blowing. My videos look cinematic now.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Lakshmi Pillai", "role": "Entrepreneur", "text": "Started my own editing service after this course. Already have 10+ clients!", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Siddharth Rao", "role": "Music Producer", "text": "Perfect for creating music videos. The effects tutorials are incredible.", "rating": 5},
    {"id": str(uuid.uuid4()), "name": "Pooja Desai", "role": "Travel Blogger", "text": "My travel videos went viral after applying these techniques. Thank you!", "rating": 5},
]

FAQS = [
    {
        "id": str(uuid.uuid4()),
        "q": "I can find free tutorials on YouTube. Why should I pay to join PranvithDOP?",
        "a": "YouTube tutorials are scattered and lack structure. PranvithDOP provides a step-by-step roadmap, real projects, lifetime access, downloadable assets, community support, and direct mentorship from a professional editor \u2014 saving you months of trial and error.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Is this course for absolute beginners, or do I need prior experience?",
        "a": "No prior experience required! We start from the absolute basics \u2014 installing software, understanding the interface \u2014 and gradually take you to advanced professional techniques.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Who is this course NOT for?",
        "a": "This course is not for people looking for quick shortcuts without practice. If you are not willing to spend time editing and applying what you learn, this is not for you.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "I have a full-time job/college. How much time do I need to dedicate daily?",
        "a": "Just 30\u201360 minutes a day is enough. The course is self-paced, so you can learn whenever you have free time \u2014 early mornings, lunch breaks, or weekends.",
    },
    {
        "id": str(uuid.uuid4()),
        "q": "Will I just be watching videos, or will I actually edit?",
        "a": "You will be editing real projects! Every module comes with practice files, assignments, and challenges that mirror real-world client work.",
    },
]

PAGES = [
    {
        "id": str(uuid.uuid4()),
        "slug": "home",
        "title": "Home",
        "sections": {
            "hero": {
                "headline": "Video Editing Mastery for Creators",
                "subheadline": "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.",
                "buttonText": "Explore Assets",
                "buttonUrl": "/assets",
                "image": "",
            },
        },
        "seo_title": "PranvithDOP \u2014 Video Editing Courses and Assets",
        "seo_description": "Premium video editing training, LUT packs, templates, and workflow resources for creators.",
        "published": True,
        "created_at": "2025-12-01T00:00:00Z",
        "updated_at": None,
    },
]

CMS_PAGES = [
    {
        "id": str(uuid.uuid4()),
        "page_key": "home",
        "title": "Home",
        "subtitle": "Premium video editing training, assets, showreels, and production services.",
        "slug": "home",
        "path": "/",
        "status": "published",
        "seo_title": "PranvithDOP - Video Editing Courses and Assets",
        "seo_description": "Premium video editing training, LUT packs, templates, and workflow resources for creators.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "courses",
        "title": "Courses",
        "subtitle": "Practical cinematic editing lessons and student outcomes.",
        "slug": "courses",
        "path": "/courses",
        "status": "published",
        "seo_title": "Courses - PranvithDOP",
        "seo_description": "Learn practical editing workflows, storytelling, color, sound, and delivery systems.",
        "settings": {"courses_enabled": False, "show_coming_soon": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "about",
        "title": "About",
        "subtitle": "DOP, filmmaker, editor, drone pilot, and visual storyteller.",
        "slug": "about",
        "path": "/about",
        "status": "published",
        "seo_title": "About - PranvithDOP",
        "seo_description": "About PranvithDOP cinematography, editing, drone, DI, and commercial visual work.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "assets",
        "title": "Assets",
        "subtitle": "Premium LUTs, sound packs, motion templates and more built for editors.",
        "slug": "assets",
        "path": "/assets",
        "status": "published",
        "seo_title": "Creative Assets - PranvithDOP",
        "seo_description": "Browse PranvithDOP digital assets for video editors and creators.",
        "settings": {"show_product_listing": True, "show_filters": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "works",
        "title": "Our Works",
        "subtitle": "A curated portfolio of cinematography, drone work, product visuals, and post-production.",
        "slug": "works",
        "path": "/works",
        "status": "published",
        "seo_title": "Our Works - PranvithDOP",
        "seo_description": "Explore PranvithDOP commercial, wedding, drone, product, film, and editing work.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "hire",
        "title": "Hire From Us",
        "subtitle": "Build a film, campaign, or visual story with cinematic intent.",
        "slug": "hire",
        "path": "/hire",
        "status": "published",
        "seo_title": "Hire PranvithDOP",
        "seo_description": "Send a project enquiry for cinematic shoots, brand films, wedding films, drone work, and edits.",
        "settings": {"show_enquiry_form": True},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "privacy",
        "title": "Privacy Policy",
        "subtitle": "Privacy Policy - Pranvith DOP",
        "slug": "privacy",
        "path": "/privacy#privacy",
        "status": "published",
        "seo_title": "Privacy Policy - PranvithDOP",
        "seo_description": "Privacy policy for PranvithDOP website, products, digital downloads, courses, and services.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
    {
        "id": str(uuid.uuid4()),
        "page_key": "terms",
        "title": "Terms & Conditions",
        "subtitle": "Legal",
        "slug": "terms",
        "path": "/privacy#terms",
        "status": "published",
        "seo_title": "Terms & Conditions - PranvithDOP",
        "seo_description": "Terms and conditions for PranvithDOP website, products, digital downloads, courses, and services.",
        "settings": {},
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    },
]


def _cms_section(page_key, section_id, section_type, title="", subtitle="", description="", button_text="", button_link="", media_type="auto", media_url="", poster_url="", data=None, enabled=True, sort_order=0):
    return {
        "id": str(uuid.uuid4()),
        "section_id": section_id,
        "page_key": page_key,
        "type": section_type,
        "title": title,
        "subtitle": subtitle,
        "description": description,
        "button_text": button_text,
        "button_link": button_link,
        "media_type": media_type,
        "media_url": media_url,
        "poster_url": poster_url,
        "data": data or {},
        "enabled": enabled,
        "sort_order": sort_order,
        "created_at": "2026-06-22T00:00:00Z",
        "updated_at": "2026-06-22T00:00:00Z",
    }


LEGAL_TERMS_ITEMS = [
    {"title": "1. Our Services", "paragraphs": ["Pranvith DOP provides digital products and creative services, including but not limited to:"], "bullets": ["Video editing services", "Photography and videography services", "VFX assets", "LUTs", "Templates", "Project files", "Presets", "Courses", "Digital downloads", "Creative resources"], "after": ["Our services are mainly intended for users in India. If you access our website from outside India, you are responsible for following your local laws."], "enabled": True, "sort_order": 0},
    {"title": "2. Intellectual Property Rights", "paragraphs": ["All content available on the Pranvith DOP website belongs to Pranvith DOP or is licensed to us.", "This includes:"], "bullets": ["Website design", "Text", "Images", "Videos", "Digital products", "Course content", "LUTs", "Templates", "Project files", "Graphics", "Logos", "Branding", "Software features"], "after": ["You are allowed to use purchased products only as per the product license.", "You may not copy, resell, share, upload, redistribute, modify, or publicly display our products or content without written permission from Pranvith DOP."], "enabled": True, "sort_order": 1},
    {"title": "3. Digital Product Usage", "paragraphs": ["When you purchase digital products from Pranvith DOP, you receive a limited license to use them for personal or professional creative work.", "You are not allowed to:"], "bullets": ["Resell our products", "Share download links with others", "Upload products to other websites", "Claim our products as your own", "Distribute files in free or paid groups", "Repackage our products and sell them"], "after": ["Any misuse may result in account suspension and legal action."], "enabled": True, "sort_order": 2},
    {"title": "4. User Responsibilities", "paragraphs": ["By using our website, you confirm that:"], "bullets": ["You are legally able to agree to these terms.", "The information you provide is true and accurate.", "You will not misuse our website or products.", "You will not use bots, scripts, or automated tools to access our website.", "You will not upload harmful files, malware, or viruses.", "You will not use our content for illegal purposes."], "enabled": True, "sort_order": 3},
    {"title": "5. User Accounts", "paragraphs": ["Some features may require you to create an account.", "You are responsible for keeping your login details safe. Pranvith DOP is not responsible for any loss caused by unauthorized access to your account."], "enabled": True, "sort_order": 4},
    {"title": "6. Products and Services", "paragraphs": ["All products and services are subject to availability.", "Pranvith DOP may update, change, remove, or discontinue any product, service, price, or offer at any time without prior notice.", "We try to display product details, previews, and descriptions clearly, but we do not guarantee that every product will match every user's expectation, software version, device, or workflow."], "enabled": True, "sort_order": 5},
    {"title": "7. Purchases and Payments", "paragraphs": ["We may accept payments through:"], "bullets": ["UPI", "Debit Card", "Credit Card", "Net Banking", "Wallets", "Razorpay or other secure payment gateways"], "after": ["All prices are shown in Indian Rupees, unless stated otherwise.", "By making a purchase, you authorize Pranvith DOP and our payment gateway partners to process your payment.", "Pranvith DOP does not store full card details or sensitive payment information."], "enabled": True, "sort_order": 6},
    {"title": "8. Digital Downloads", "paragraphs": ["After successful payment, digital products may be delivered through download links, email, user account access, or website download pages.", "You are responsible for downloading and saving your purchased files safely.", "Download access may be limited, removed, or blocked if misuse, fraud, or unauthorized sharing is detected."], "enabled": True, "sort_order": 7},
    {"title": "9. Refund Policy", "paragraphs": ["All digital product sales are final and non-refundable.", "Refunds are not provided once a digital product, course, download, template, LUT, preset, or project file has been purchased or accessed.", "For service-based work, refund or cancellation terms may depend on the project stage and agreement.", "Please check product details carefully before purchasing."], "enabled": True, "sort_order": 8},
    {"title": "10. Courses", "paragraphs": ["Course content is provided for learning and educational purposes.", "You may not record, resell, share, copy, or distribute course videos, notes, files, or private materials without permission from Pranvith DOP.", "Access to courses may be removed if misuse is detected."], "enabled": True, "sort_order": 9},
    {"title": "11. Prohibited Activities", "paragraphs": ["You agree not to:"], "bullets": ["Steal or misuse user information", "Copy or misuse Pranvith DOP content", "Resell or redistribute our digital products", "Upload malware or harmful files", "Harass, abuse, or harm other users", "Use our website for illegal activities", "Try to hack, damage, or overload the website", "Use our intellectual property to compete against Pranvith DOP"], "after": ["Violation of these rules may result in account suspension, permanent ban, cancellation of access, and legal action."], "enabled": True, "sort_order": 10},
    {"title": "12. User Content", "paragraphs": ["If you submit reviews, comments, testimonials, messages, uploads, or feedback, you allow Pranvith DOP to use, display, reproduce, and publish that content for website, marketing, and service-related purposes.", "You still own your content, but you give Pranvith DOP permission to use it."], "enabled": True, "sort_order": 11},
    {"title": "13. Reviews and Testimonials", "paragraphs": ["Reviews must be honest and respectful.", "Reviews must not contain:"], "bullets": ["Fake or misleading information", "Offensive language", "Abuse or harassment", "Discrimination", "Illegal content", "Spam or promotional links"], "after": ["Pranvith DOP may remove reviews that violate these rules."], "enabled": True, "sort_order": 12},
    {"title": "14. Social Media", "paragraphs": ["Our website may include links to Instagram, YouTube, WhatsApp, or other third-party platforms.", "Pranvith DOP is not responsible for third-party platform content, privacy policies, or technical issues."], "enabled": True, "sort_order": 13},
    {"title": "15. Website Management", "paragraphs": ["Pranvith DOP may monitor website activity to protect users, prevent fraud, improve security, and enforce these terms.", "We may restrict, suspend, or remove access if a user violates these Terms & Conditions."], "enabled": True, "sort_order": 14},
    {"title": "16. Privacy Policy", "paragraphs": ["By using Pranvith DOP, you also agree to our Privacy Policy mentioned below."], "enabled": True, "sort_order": 15},
    {"title": "17. Termination", "paragraphs": ["Pranvith DOP may suspend or terminate your account, download access, course access, or service access without notice if you violate these Terms & Conditions."], "enabled": True, "sort_order": 16},
    {"title": "18. Service Changes and Downtime", "paragraphs": ["Our website or services may sometimes be updated, changed, interrupted, or temporarily unavailable.", "Pranvith DOP is not responsible for any loss caused by downtime, technical issues, updates, or service interruptions."], "enabled": True, "sort_order": 17},
    {"title": "19. Governing Law", "paragraphs": ["These Terms & Conditions are governed by the laws of India."], "enabled": True, "sort_order": 18},
    {"title": "20. Dispute Resolution", "paragraphs": ["Any disputes related to Pranvith DOP, our website, products, or services will be handled under applicable Indian laws."], "enabled": True, "sort_order": 19},
    {"title": "21. WhatsApp Communication Consent", "paragraphs": ["By providing your phone number, you agree to receive important updates from Pranvith DOP through WhatsApp, SMS, email, or phone call.", "These messages may include:"], "bullets": ["Order updates", "Download updates", "Service updates", "Course updates", "Support messages", "Payment-related communication"], "after": ["You can withdraw your consent anytime by contacting us."], "enabled": True, "sort_order": 20},
    {"title": "22. Contact Us", "paragraphs": ["Pranvith DOP", "Website: https://pranvithdop.com", "Email: info@pranvithdop.com", "Phone: +91 9059867883", "Location: India"], "enabled": True, "sort_order": 21},
]


LEGAL_PRIVACY_ITEMS = [
    {"title": "1. Information We Collect", "paragraphs": ["We may collect the following information:", "Personal Information"], "bullets": ["Name", "Email address", "Phone number", "Billing details", "Account details", "Social media username, if provided"], "after": ["Technical Information", "IP address, device details, browser details, cookies, website usage data, and analytics data.", "Transaction Information", "Purchase history, order details, payment status, and download access details.", "Payment information is processed securely by our payment gateway partners. Pranvith DOP does not store full card numbers or sensitive banking information."], "enabled": True, "sort_order": 0},
    {"title": "2. How We Use Your Information", "paragraphs": ["We use your information to:"], "bullets": ["Deliver digital products", "Provide download access", "Manage course access", "Process payments", "Provide customer support", "Send order and service updates", "Improve website performance", "Improve website security", "Prevent fraud and misuse", "Contact you about your purchase or service request"], "enabled": True, "sort_order": 1},
    {"title": "3. Data Sharing", "paragraphs": ["Pranvith DOP does not sell your personal data.", "We may share your information only with:"], "bullets": ["Payment gateway providers", "Hosting and website service providers", "Email or communication service providers", "Analytics and security tools", "Legal authorities, if required by law"], "after": ["We only share information when it is necessary to operate our website, deliver services, or follow legal requirements."], "enabled": True, "sort_order": 2},
    {"title": "4. Data Security", "paragraphs": ["Pranvith DOP uses reasonable security measures to protect your information.", "However, no online system is 100% secure. We cannot guarantee complete security of data transmitted through the internet."], "enabled": True, "sort_order": 3},
    {"title": "5. Data Retention", "paragraphs": ["We keep your information only as long as needed to:"], "bullets": ["Provide products and services", "Maintain order records", "Provide support", "Prevent fraud", "Comply with legal requirements"], "enabled": True, "sort_order": 4},
    {"title": "6. Your Rights", "paragraphs": ["You may request:"], "bullets": ["Access to your personal data", "Correction of incorrect data", "Deletion of your account or data"], "after": ["To request this, contact us by email."], "enabled": True, "sort_order": 5},
    {"title": "7. Cookies", "paragraphs": ["Our website may use cookies to:"], "bullets": ["Improve user experience", "Remember preferences", "Track website performance", "Analyze traffic", "Improve security"], "after": ["You can disable cookies through your browser settings."], "enabled": True, "sort_order": 6},
    {"title": "8. Minors", "paragraphs": ["Users under 18 should use our website and services only with parent or guardian supervision."], "enabled": True, "sort_order": 7},
    {"title": "9. Third-Party Links", "paragraphs": ["Our website may contain links to third-party websites such as Instagram, YouTube, payment gateways, or other platforms.", "Pranvith DOP is not responsible for the content, privacy policies, or security practices of third-party websites."], "enabled": True, "sort_order": 8},
    {"title": "10. Marketing and Communication", "paragraphs": ["We may contact you through email, phone, SMS, or WhatsApp for:"], "bullets": ["Order updates", "Download support", "Course updates", "Service updates", "Offers and announcements", "Customer support"], "after": ["You may request to stop receiving promotional messages anytime."], "enabled": True, "sort_order": 9},
    {"title": "11. Changes to This Privacy Policy", "paragraphs": ["Pranvith DOP may update this Privacy Policy from time to time.", "Continued use of our website or services after updates means you accept the revised policy."], "enabled": True, "sort_order": 10},
    {"title": "12. Contact for Privacy Questions", "paragraphs": ["For privacy-related questions, contact:", "Pranvith DOP", "Website: https://pranvithdop.com", "Email: info@pranvithdop.com", "Phone: +91 9059867883", "Location: India"], "enabled": True, "sort_order": 11},
]


CMS_SECTIONS = [
    _cms_section("home", "hero", "hero", "Video Editing Mastery for Creators", "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.", "Master the art of video editing with comprehensive courses, creative assets, showreels, and production services.", "Explore Assets", "/assets", sort_order=0, data={"secondary_button_text": "Book a Project", "secondary_button_link": "/hire"}),
    _cms_section("home", "featured-assets", "portfolio_grid", "Cinematic work, cleanly presented.", "Our Works", "Selected films, commercial visuals, drone sequences, and edits from the PranvithDOP portfolio.", "VIEW ALL WORKS", "/works", data={"items": [
        {"title": "Luxury Brand Commercial", "category": "Commercial", "description": "A polished commercial film with controlled lighting, cinematic movement, and premium product framing.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 0},
        {"title": "Cinematic Wedding Story", "category": "Wedding", "description": "Emotion-led wedding cinematography built around light, movement, vows, and family moments.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 1},
        {"title": "Aerial Location Film", "category": "Drone", "description": "Drone-led visuals for real estate, travel, and production establishing sequences.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 2},
    ]}, sort_order=1),
    _cms_section("home", "instagram-profile", "gallery", "Transform your creative vision into reality.", "", "Master professional video editing skills with our comprehensive courses. Learn industry-standard techniques, creative storytelling, and advanced workflows that bring your ideas to life.", "Get started", "/courses", data={
        "username": "pranvith_dop",
        "display_name": "Pranvith Dop",
        "followers_count": "5,131",
        "following_count": "10",
        "bio_line_1": "DOP | Filmmaker | Video Editor",
        "bio_line_2": "Drone Pilot | DI",
        "bio_line_3": "Product & Commercial Photography",
        "bio_line_4": "Graphic Design",
        "link_text": "youtube.com/@pranvithdop",
        "link_url": "https://www.youtube.com/@pranvithdop",
        "follow_button_url": "https://www.instagram.com/pranvith_dop",
        "items": [
            {"title": "Cinematic editing reel", "type": "Reel", "coverText": "EDIT REEL", "enabled": True, "sort_order": 0},
            {"title": "Behind the scenes", "type": "Post", "coverText": "BTS", "enabled": True, "sort_order": 1},
            {"title": "Drone shot preview", "type": "Video", "coverText": "DRONE", "enabled": True, "sort_order": 2},
        ],
    }, sort_order=2),
    _cms_section("home", "services", "services_cards", "Services", "Cinematic production and post-production support.", data={"items": [
        {"title": "Film Production", "description": "Narrative, branded, and creator-led films designed around story, light, and pacing.", "button_link": "/commercial-video-production", "enabled": True},
        {"title": "Wedding Cinematography", "description": "Emotional wedding films with cinematic framing, audio, drone visuals, and premium edits.", "button_link": "/wedding-cinematography", "enabled": True},
        {"title": "Commercial Ads", "description": "Campaign-ready ads for products, creators, local businesses, and digital launches.", "button_link": "/commercial-video-production", "enabled": True},
        {"title": "Drone Cinematography", "description": "Licensed aerial visuals for locations, events, real estate, and cinematic sequences.", "button_link": "/drone-cinematography", "enabled": True},
        {"title": "Video Editing", "description": "Editing, color grading, titles, sound polish, reels, YouTube videos, and brand films.", "button_link": "/hire", "enabled": True},
        {"title": "Product & Commercial Photography", "description": "Clean product, campaign, and commercial photography for digital-first brands.", "button_link": "/hire", "enabled": True},
    ]}, sort_order=3),
    _cms_section("home", "showreel", "showreel", "Featured Showreel", "A cinematic portfolio of light, movement, and emotion.", "Commercials, wedding stories, drone sequences, product frames, and post-production work shaped for premium digital delivery.", "View all works", "/works", data={"items": [
        {"title": "Cinematic Wedding Story", "category": "Wedding", "description": "Emotion-led wedding cinematography built around light, movement, vows, and family moments.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 0},
        {"title": "Aerial Location Film", "category": "Drone", "description": "Drone-led visuals for real estate, travel, and production establishing sequences.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 1},
        {"title": "Editing & DI Suite", "category": "Editing", "description": "Full post-production workflow: edit, grade, sound polish, titles, and final delivery.", "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "enabled": True, "sort_order": 2},
    ]}, sort_order=4),
    _cms_section("home", "cta", "cta", "Ready to create cinematic visuals?", "", "Explore assets, courses, showreels, and production services built for serious creators.", "Book a Project", "/hire", sort_order=5),
    _cms_section("home", "faq", "faq", "Have Questions?", "We've Answered Them.", "From tools to timelines to placements, get full clarity before you take the next step.", "Contact Us", "/hire", data={"items": [
        {"question": "Can I hire PranvithDOP for a shoot?", "answer": "Yes. Use the hire page to share your project type, date, location, and requirements.", "enabled": True, "sort_order": 0},
        {"question": "Are assets delivered digitally?", "answer": "Yes. Digital assets are delivered online after checkout or free access confirmation.", "enabled": True, "sort_order": 1},
    ]}, sort_order=6),
    _cms_section("courses", "coming-soon", "cta", "Courses Coming Soon", "We are preparing premium video editing courses. Stay tuned.", "", "Explore Assets", "/assets", sort_order=0),
    _cms_section("courses", "hero", "hero", "Master Cinematic Video Editing", "Learn practical editing workflows, storytelling, color, sound, and delivery systems for real creator and client projects.", "", "Explore Courses", "#courses", sort_order=1),
    _cms_section("courses", "right-for-you", "services_cards", "IS THIS COURSE RIGHT FOR YOU?", "", "", "Start Now", "/courses", data={"cta_text": "UPGRADE YOUR EDITING SKILLS NOW", "items": [
        {"title": "Beginners", "description": "You want a practical foundation without getting lost in technical clutter.", "enabled": True, "sort_order": 0},
        {"title": "Creators", "description": "You make reels, YouTube videos, or client edits and want stronger storytelling.", "enabled": True, "sort_order": 1},
        {"title": "Freelancers", "description": "You need repeatable workflows for paid editing and post-production projects.", "enabled": True, "sort_order": 2},
        {"title": "Filmmakers", "description": "You want better rhythm, color, sound polish, and final delivery confidence.", "enabled": True, "sort_order": 3},
    ]}, sort_order=2),
    _cms_section("courses", "what-youll-learn", "course_showcase", "What You'll Learn", "Skills that turn timelines into stories.", data={"items": [
        {"title": "Premiere Pro Workflow", "description": "Build clean timelines, organize footage, cut faster, and export professionally.", "enabled": True},
        {"title": "After Effects Motion", "description": "Create titles, motion graphics, transitions, and polished visual effects.", "enabled": True},
        {"title": "AI Editing Tools", "description": "Use modern AI tools to speed up captions, cleanup, reframing, and creative workflows.", "enabled": True},
    ]}, sort_order=3),
    _cms_section("courses", "course-list", "course_showcase", "MASTER VIDEO EDITING", "Choose a course and start learning with practical, cinematic workflows.", data={"show_course_list": True}, sort_order=4),
    _cms_section("courses", "student-videos", "video_reviews", "Student Video Reviews", data={"items": []}, sort_order=5),
    _cms_section("courses", "student-reviews", "testimonials", "Student Reviews", data={"items": []}, sort_order=6),
    _cms_section("courses", "faq", "faq", "FAQ", "", data={"items": [
        {"question": "Do I need prior editing experience?", "answer": "No. The course content is beginner-friendly and moves into practical professional workflows.", "enabled": True},
    ]}, sort_order=7),
    _cms_section("about", "hero", "image_text", "DOP, filmmaker, editor, drone pilot, and visual storyteller.", "About Pranvith Dop", "PranvithDOP creates cinematic visuals for brands, creators, weddings, products, and digital campaigns.", "Book a project", "/hire", "image", "/assets/brand-profile.png", sort_order=0),
    _cms_section("about", "stats", "services_cards", "Creative Highlights", "", data={"items": [
        {"title": "250+", "description": "Film, ad & edit projects", "enabled": True},
        {"title": "80+", "description": "Product and commercial shoots", "enabled": True},
        {"title": "120+", "description": "Aerial/drone sequences", "enabled": True},
        {"title": "3,000+", "description": "Post-production hours", "enabled": True},
    ]}, sort_order=1),
    _cms_section("about", "creative-positioning", "text", "Creative positioning", "", "Built for clients who need more than footage: visual direction, cinematic lighting, clean edit structure, tasteful color, and final assets ready for web, social, campaigns, and events.", sort_order=2),
    _cms_section("about", "gear-workflow", "services_cards", "Gear & workflow", "", data={"items": [
        {"title": "Cinema camera workflow", "enabled": True, "sort_order": 0},
        {"title": "Drone cinematography", "enabled": True, "sort_order": 1},
        {"title": "Gimbal movement", "enabled": True, "sort_order": 2},
        {"title": "Wireless audio capture", "enabled": True, "sort_order": 3},
        {"title": "DaVinci Resolve DI", "enabled": True, "sort_order": 4},
        {"title": "Premiere Pro and After Effects", "enabled": True, "sort_order": 5},
        {"title": "Product lighting setups", "enabled": True, "sort_order": 6},
        {"title": "Commercial editing pipeline", "enabled": True, "sort_order": 7},
    ]}, sort_order=3),
    _cms_section("assets", "hero", "hero", "Creative Assets Store", "Premium LUTs, sound packs, motion templates and more - built for editors.", "", "", "", sort_order=0),
    _cms_section("works", "hero", "hero", "Films, commercials, aerials, and edits crafted for impact.", "PORTFOLIO", "A curated portfolio of PranvithDOP cinematography, drone work, product visuals, and post-production projects.", sort_order=0),
    _cms_section("works", "showreel", "showreel", "A cinematic portfolio of light, movement, and emotion.", "FEATURED SHOWREEL", "Commercials, wedding stories, drone sequences, product frames, and post-production work shaped for premium digital delivery.", "View all works", "/works", sort_order=1),
    _cms_section("works", "projects", "portfolio_grid", "Portfolio Projects", "", data={"items": []}, sort_order=2),
    _cms_section("works", "client-testimonials", "testimonials", "Trusted for films, brands, weddings, and launch visuals.", "Client words", data={"items": [
        {"title": "Arjun Reddy", "subtitle": "Commercial Film", "description": "The visuals felt premium from the first frame. The lighting, movement, and edit gave our campaign a real production-house finish.", "rating": 5, "enabled": True, "sort_order": 0},
        {"title": "Meera & Karthik", "subtitle": "Wedding Film", "description": "Our wedding film feels emotional and cinematic without looking forced. Every important moment was captured beautifully.", "rating": 5, "enabled": True, "sort_order": 1},
        {"title": "Saanvi Studio", "subtitle": "Product Campaign", "description": "Fast, precise, and tasteful. The product frames and reels were ready for ads and social launch.", "rating": 5, "enabled": True, "sort_order": 2},
    ]}, sort_order=3),
    _cms_section("works", "cta", "cta", "Ready to build the next frame?", "", "Share your project and we will shape a visual plan around the story.", "Hire PranvithDOP", "/hire", sort_order=4),
    _cms_section("hire", "hero", "hero", "Build a film, campaign, or visual story with cinematic intent.", "Book PranvithDOP", "Tell us about your shoot, brand film, wedding, reel, product campaign, or edit. We will shape the look, schedule, and creative plan around the story you want people to feel.", sort_order=0),
    _cms_section("hire", "services", "services_cards", "What We Can Build", "", data={"items": [
        {"title": "Cinematic wedding, commercial, drone, and brand storytelling", "enabled": True},
        {"title": "DOP-led planning for light, movement, locations, and edit mood", "enabled": True},
        {"title": "Editing, DI, product photography, and creative design support", "enabled": True},
        {"title": "Clear project scope, timeline, and delivery expectations", "enabled": True},
        {"title": "Flexible packages for shoots, campaigns, reels, and full films", "enabled": True},
    ]}, sort_order=1),
    _cms_section("hire", "info-cards", "services_cards", "Project Planning Info", "", data={"items": [
        {"title": "Plan the shoot", "description": "Share your date, location, budget, and visual references.", "enabled": True},
        {"title": "Shoot anywhere", "description": "Available for local, destination, commercial, and drone projects.", "enabled": True},
    ]}, sort_order=2),
    _cms_section("hire", "enquiry-form", "contact_form", "Start a project enquiry", "", "A few details are enough. We will follow up with the right next step.", "Send Project Enquiry", "/hire", data={
        "name_label": "Name",
        "name_placeholder": "Your name",
        "email_label": "Email",
        "email_placeholder": "you@example.com",
        "phone_label": "Phone",
        "phone_placeholder": "+91 ...",
        "project_type_label": "Project type",
        "project_type_placeholder": "Select type",
        "project_types": ["Commercial Ad", "Wedding Cinematography", "Drone Shoot", "Product Shoot", "Film / Music Video", "Editing / DI", "Other"],
        "message_label": "Message",
        "message_placeholder": "Tell us the story, format, deliverables, references, and timeline...",
        "submit_button_text": "Send Project Enquiry",
        "success_message": "Request sent!",
        "validation_message": "Please enter your name, email, and project message",
    }, sort_order=3),
    _cms_section("terms", "legal-sections", "text", "Terms & Conditions", "Legal", "These Terms & Conditions are a legal agreement between you and Pranvith DOP. By using our website, products, digital assets, courses, services, or any related content, you agree to follow these terms.", data={
        "intro_after": "Please read these terms carefully. If you do not agree, please do not use our website or services.",
        "items": LEGAL_TERMS_ITEMS,
    }, sort_order=0),
    _cms_section("privacy", "legal-sections", "text", "Privacy Policy", "Last Updated: 23 June 2026", "This Privacy Policy explains how Pranvith DOP collects, uses, stores, and protects your information when you use our website, products, digital downloads, courses, and services.", data={
        "intro_after": "By using our website or services, you agree to this Privacy Policy.",
        "items": LEGAL_PRIVACY_ITEMS,
    }, sort_order=0),
]

# ---------- 8 ASSETS WITH FULL CMS CONTENT ----------
_COMPAT_VIDEO = ["Adobe Premiere Pro", "DaVinci Resolve", "Final Cut Pro", "After Effects"]
_COMPAT_AUDIO = ["Premiere Pro", "Final Cut Pro", "DaVinci Resolve", "Logic Pro"]
_COMPAT_FONTS = ["After Effects", "Premiere Pro", "Photoshop", "Illustrator"]

ASSET_PRODUCTS = [
    {
        "id": str(uuid.uuid4()),
        "slug": "creative-lut-pack",
        "name": "Creative LUT Pack",
        "category": "LUT Pack",
        "price": 49,
        "sale_price": 49,
        "is_free": False,
        "description": "Pranvith Creative LUT Pack \u2014 a curated set of cinematic 3D LUTs for film-quality color grades in one click.",
        "features": [
            "10+ cinematic 3D LUTs",
            "One-click professional grading",
            "Works with LOG, RAW & standard footage",
            "Beginner-friendly install guide",
            "Lifetime updates",
            "Compatible with major editing software",
        ],
        "benefits": ["Save grading time", "Premium cinematic look", "Client-ready in minutes"],
        "faqs": [
            {"q": "Which apps work with this pack?", "a": "Premiere Pro, DaVinci Resolve, Final Cut Pro, After Effects and any editor that supports 3D LUT imports."},
            {"q": "Do I need advanced editing skills?", "a": "No. The LUTs are drag-and-drop. A simple import is all you need."},
            {"q": "How do I receive the files?", "a": "After payment you\u2019re redirected to a dedicated thank-you page with the instant download link and install instructions."},
            {"q": "Do I get updates?", "a": "Yes. Future updates are included with your purchase."},
        ],
        "images": [IMG_CREATIVE_LUT],
        "hero_image": IMG_CREATIVE_LUT,
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/creative-lut-pack.zip",
        "payment_link": "https://rzp.io/rzp/yThuB5K",
        "landing_content": _landing(
            "Pranvith Creative LUT Pack",
            "Give your videos the cinematic grade used by professional filmmakers.",
            [
                "Professional Cinematic Look",
                "Works Instantly",
                "Saves Editing Time",
                "Beginner Friendly",
                "Professional Color Science",
                "Compatible with major editors",
            ],
            "Flat, ungraded footage versus a film-grade cinematic finish with depth and contrast.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b949 one-time", "\u20b9499+"],
                ["Support", "Direct email support", "Limited or none"],
                ["Ease of Use", "One-click install", "Manual setup"],
                ["Quality", "Cinematic color science", "Generic grades"],
                ["Updates", "Included with purchase", "Extra charge"],
            ],
            [
                {"q": "Can I use these LUTs with any editing software?", "a": "Yes \u2014 Premiere Pro, DaVinci Resolve, Final Cut Pro, After Effects and any 3D-LUT-capable editor."},
                {"q": "Will the LUTs work with my footage?", "a": "Yes. Calibrated for RAW, LOG and standard formats."},
                {"q": "Will I get updates?", "a": "Yes \u2014 included with your purchase."},
            ],
        ),
        "thank_you_content": _thanks(
            "Thank you for your purchase!",
            "Your Pranvith Creative LUT Pack is ready. Use the download button below to grab the .zip file.",
            [
                "Unzip the downloaded archive on your computer.",
                "Open your editor (Premiere Pro / DaVinci / Final Cut).",
                "Import the LUT files via your color panel.",
                "Apply the LUT and adjust intensity to taste.",
            ],
        ),
        "seo_title": "Creative LUT Pack \u2014 PranvithDOP",
        "seo_description": "Premium cinematic 3D LUTs for one-click professional color grading.",
        "published": True,
        "created_at": "2025-12-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/creative-lut-pack",
        "sold_count": 12,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "premiere-pro-wedding-templates",
        "name": "Premiere Pro Wedding Templates",
        "category": "Templates",
        "price": 299,
        "sale_price": 299,
        "is_free": False,
        "description": "Animated Premiere Pro templates engineered for cinematic wedding edits \u2014 invitations, openers, lower thirds and more.",
        "features": [
            "10+ ready-to-use wedding templates",
            "Drag-and-drop in Premiere Pro",
            "Editable text & color",
            "4K resolution",
            "Cinematic typography",
            "Free updates",
        ],
        "benefits": ["Save hours of design", "Premium wedding aesthetic", "Easy client customisation"],
        "faqs": [
            {"q": "Which Premiere Pro version is required?", "a": "Premiere Pro CC 2020 or later."},
            {"q": "Can I customise text and music?", "a": "Yes \u2014 every layer is fully editable."},
            {"q": "Are these for commercial use?", "a": "Yes, you can use them in client wedding deliverables."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/premiere-pro-wedding-templates.zip",
        "payment_link": "https://rzp.io/rzp/ol7TMWt",
        "landing_content": _landing(
            "Premiere Pro Wedding Templates",
            "Cinematic wedding edits in a fraction of the time.",
            [
                "Wedding invitations",
                "Animated openers",
                "Lower thirds",
                "Save-the-date templates",
                "Modern film aesthetic",
                "4K resolution",
            ],
            "Plain wedding edits vs. cinematic, story-driven sequences with elegant typography.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b9299 one-time", "\u20b91499+"],
                ["Format", "Editable .prproj", "Locked exports"],
                ["Customisation", "Full text/colour", "Limited"],
                ["Updates", "Included", "Extra charge"],
            ],
            [
                {"q": "Do I need any plugins?", "a": "No \u2014 templates run on stock Premiere Pro."},
                {"q": "Can I export in any resolution?", "a": "Yes, the project is 4K and exports to any common spec."},
            ],
        ),
        "thank_you_content": _thanks(
            "Welcome to the Wedding Template family!",
            "Your Premiere Pro Wedding Templates are ready. Download below and follow the install guide.",
            [
                "Unzip the project files.",
                "Open the .prproj inside Premiere Pro.",
                "Replace the placeholder text with your details.",
                "Render at your delivery resolution.",
            ],
        ),
        "seo_title": "Premiere Pro Wedding Templates \u2014 PranvithDOP",
        "seo_description": "Cinematic, fully editable Premiere Pro templates for wedding editors.",
        "published": True,
        "created_at": "2025-11-15T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/premiere-pro-wedding-templates",
        "sold_count": 24,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "cinematic-sound-fx-pack",
        "name": "Cinematic Sound FX Pack",
        "category": "Sound FX",
        "price": 149,
        "sale_price": 149,
        "is_free": False,
        "description": "A curated set of cinematic impacts, risers, whooshes and atmospheres for premium video edits.",
        "features": [
            "100+ cinematic SFX",
            "Impacts, risers, whooshes",
            "Royalty-free for client work",
            "High-quality 24-bit WAV",
            "Organised by category",
            "Drag-and-drop ready",
        ],
        "benefits": ["Boost production value", "Faster sound design", "Pro-level cinematic feel"],
        "faqs": [
            {"q": "Are these royalty-free?", "a": "Yes, royalty-free for personal and client projects."},
            {"q": "What format are the files?", "a": "High-quality 24-bit WAV."},
        ],
        "images": [IMG_SOUND_FX],
        "hero_image": IMG_SOUND_FX,
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/cinematic-sound-fx-pack.zip",
        "payment_link": "https://rzp.io/rzp/2XRdX6KE",
        "landing_content": _landing(
            "Cinematic Sound FX Pack",
            "Premium cinematic sound design for editors who want production-grade impact.",
            [
                "100+ cinematic SFX",
                "Impacts & risers",
                "Whooshes & transitions",
                "Atmospheres & drones",
                "Royalty-free",
                "Organised library",
            ],
            "Edits that feel flat vs. immersive, cinematic moments driven by tasteful sound design.",
            _COMPAT_AUDIO,
            [
                ["Price", "\u20b9149 one-time", "\u20b9999+"],
                ["Format", "24-bit WAV", "Compressed MP3"],
                ["Royalty", "Free for clients", "Subscription only"],
            ],
            [
                {"q": "Will this work on a Mac?", "a": "Yes \u2014 WAV files work on all major platforms."},
                {"q": "Is there a music license?", "a": "These are sound effects \u2014 royalty-free for editing use."},
            ],
        ),
        "thank_you_content": _thanks(
            "Sound design unlocked!",
            "Your Cinematic Sound FX Pack is ready to download.",
            [
                "Unzip the archive.",
                "Place the folder in your sound library.",
                "Drag the WAVs onto your timeline.",
                "Mix to taste.",
            ],
        ),
        "seo_title": "Cinematic Sound FX Pack \u2014 PranvithDOP",
        "seo_description": "Premium 24-bit WAV cinematic sound effects, royalty-free for editing projects.",
        "published": True,
        "created_at": "2025-11-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/cinematic-sound-fx-pack",
        "sold_count": 8,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "after-effects-title-templates",
        "name": "After Effects Title Templates",
        "category": "Templates",
        "price": 199,
        "sale_price": 199,
        "is_free": False,
        "description": "Animated title templates and lower thirds for After Effects \u2014 cinematic, editable and ready to drop in.",
        "features": [
            "20+ animated titles",
            "Lower thirds included",
            "Editable text & colour",
            "AE 2020+ compatible",
            "4K resolution",
            "Lifetime updates",
        ],
        "benefits": ["Save design time", "Cinematic typography", "Story-friendly motion"],
        "faqs": [
            {"q": "Which After Effects version is required?", "a": "After Effects CC 2020 or later."},
            {"q": "Can I edit colours and fonts?", "a": "Yes, fully editable."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/after-effects-title-templates.zip",
        "payment_link": "https://rzp.io/rzp/8eKZEb7v",
        "landing_content": _landing(
            "After Effects Title Templates",
            "Drop-in cinematic titles and lower thirds that elevate any edit.",
            [
                "20+ animated titles",
                "Lower thirds",
                "Editable text & colour",
                "AE 2020+ compatible",
                "Modular structure",
                "Lifetime updates",
            ],
            "Edits with static titles vs. dynamic, story-driven motion typography.",
            _COMPAT_VIDEO,
            [
                ["Price", "\u20b9199 one-time", "\u20b91499+"],
                ["Editability", "Full text/colour", "Limited"],
                ["Resolution", "4K", "1080p"],
            ],
            [
                {"q": "Does this work in Premiere Pro?", "a": "Designed for AE \u2014 you can export and use the result in Premiere Pro."},
                {"q": "Do I need plugins?", "a": "No additional plugins required."},
            ],
        ),
        "thank_you_content": _thanks(
            "Titles unlocked!",
            "Your After Effects Title Templates are ready.",
            [
                "Unzip the archive.",
                "Open the .aep project in After Effects.",
                "Edit the text & colour in the comp panel.",
                "Render and import into your edit.",
            ],
        ),
        "seo_title": "After Effects Title Templates \u2014 PranvithDOP",
        "seo_description": "Cinematic animated title templates and lower thirds for After Effects.",
        "published": True,
        "created_at": "2025-10-20T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/after-effects-title-templates",
        "sold_count": 18,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "royalty-free-music-bundle",
        "name": "Royalty-Free Music Bundle",
        "category": "Music",
        "price": 249,
        "sale_price": 249,
        "is_free": False,
        "description": "A bundle of cinematic, upbeat and emotional royalty-free tracks for editors and creators.",
        "features": [
            "30+ original tracks",
            "Cinematic, upbeat & emotional moods",
            "Multiple track lengths",
            "Royalty-free for client work",
            "High-quality WAV & MP3",
            "Lifetime updates",
        ],
        "benefits": ["Faster scoring", "No copyright strikes", "Premium production"],
        "faqs": [
            {"q": "Can I use these in client work?", "a": "Yes \u2014 fully royalty-free."},
            {"q": "What formats are included?", "a": "High-quality WAV and MP3."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/royalty-free-music-bundle.zip",
        "payment_link": "https://rzp.io/rzp/GmCfBooE",
        "landing_content": _landing(
            "Royalty-Free Music Bundle",
            "Cinematic, upbeat and emotional tracks to score any edit.",
            [
                "30+ tracks",
                "Cinematic moods",
                "Upbeat tracks",
                "Emotional pieces",
                "Royalty-free",
                "Lifetime updates",
            ],
            "Edits scored with stock loops vs. compositions that feel handcrafted for the story.",
            _COMPAT_AUDIO,
            [
                ["Price", "\u20b9249 one-time", "\u20b91299+"],
                ["License", "Royalty-free", "Subscription"],
                ["Track count", "30+", "10\u201320"],
            ],
            [
                {"q": "Do I need to credit Pranvith?", "a": "Crediting is appreciated but not required."},
                {"q": "Can I use these on YouTube?", "a": "Yes \u2014 royalty-free for streaming platforms."},
            ],
        ),
        "thank_you_content": _thanks(
            "Music bundle unlocked!",
            "Your Royalty-Free Music Bundle is ready.",
            [
                "Unzip the archive.",
                "Browse the tracks by mood folder.",
                "Drag the file into your edit.",
                "Mix to your scene.",
            ],
        ),
        "seo_title": "Royalty-Free Music Bundle \u2014 PranvithDOP",
        "seo_description": "Premium royalty-free music for editors \u2014 cinematic, upbeat and emotional tracks.",
        "published": True,
        "created_at": "2025-10-10T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/royalty-free-music-bundle",
        "sold_count": 25,
    },
    # ---------- FREE assets ----------
    {
        "id": str(uuid.uuid4()),
        "slug": "smooth-transitions-pack",
        "name": "Smooth Transitions Pack",
        "category": "Transitions",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free pack of modern transitions for reels, YouTube videos, and short-form content.",
        "features": [
            "20+ smooth transitions",
            "Camera moves",
            "Zoom & spin transitions",
            "Drag-and-drop ready",
            "Compatible with major editors",
            "Free forever",
        ],
        "benefits": ["Faster editing", "Smooth visual flow", "Reels-ready polish"],
        "faqs": [
            {"q": "Are these really free?", "a": "Yes \u2014 100% free."},
            {"q": "Can I use these commercially?", "a": "Yes, for personal and client projects."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/smooth-transitions-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Smooth Transitions Pack",
            "Modern transitions to make every cut feel intentional.",
            [
                "20+ transitions",
                "Camera moves",
                "Zoom transitions",
                "Spin & whip",
                "Drag-and-drop",
                "Free forever",
            ],
            "Hard cuts that feel jarring vs. smooth movement that pulls the viewer forward.",
            _COMPAT_VIDEO,
            [
                ["Price", "FREE", "\u20b9499+"],
                ["Use", "Personal & client", "Personal only"],
            ],
            [
                {"q": "How do I install?", "a": "Drag the .mogrt files into your editor and drop onto your timeline."},
                {"q": "Will this work on M-series Macs?", "a": "Yes."},
            ],
        ),
        "thank_you_content": _thanks(
            "Transitions unlocked!",
            "Your Smooth Transitions Pack is ready.",
            [
                "Click Download below.",
                "Unzip the archive.",
                "Drop the transitions on your timeline.",
                "Adjust the duration to your cut.",
            ],
        ),
        "seo_title": "Smooth Transitions Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "Free pack of modern transitions for reels and short-form video editors.",
        "published": True,
        "created_at": "2025-09-15T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/smooth-transitions-pack",
        "sold_count": 0,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "color-gradients-pack",
        "name": "Color Gradients Pack",
        "category": "Gradients",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free set of premium color gradients for designers, editors and motion artists.",
        "features": [
            "50+ gradients",
            "Hand-crafted palettes",
            "Use in After Effects, Premiere & Photoshop",
            "PNG + .grd format",
            "Free for commercial use",
            "Updates included",
        ],
        "benefits": ["Faster design", "Modern aesthetic", "Premium colour stories"],
        "faqs": [
            {"q": "Where can I use these gradients?", "a": "Any design or video tool that accepts gradient swatches or PNGs."},
            {"q": "Is this free for commercial use?", "a": "Yes."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/color-gradients-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Color Gradients Pack",
            "Premium gradient palettes for designers, editors and motion artists.",
            [
                "50+ gradients",
                "Hand-crafted palettes",
                "PNG + .grd",
                "Photoshop swatches",
                "Free commercial use",
                "Updates included",
            ],
            "Edits that feel flat vs. modern, gradient-driven palettes that carry the brand.",
            ["Premiere Pro", "After Effects", "Photoshop", "Figma"],
            [
                ["Price", "FREE", "\u20b9299+"],
                ["License", "Commercial OK", "Personal only"],
            ],
            [
                {"q": "How do I import the gradients?", "a": "Load the .grd in Photoshop, or use the PNGs as overlays."},
                {"q": "Can I tweak the colours?", "a": "Yes \u2014 every gradient is editable."},
            ],
        ),
        "thank_you_content": _thanks(
            "Gradients unlocked!",
            "Your Color Gradients Pack is ready.",
            [
                "Unzip the archive.",
                "Open the .grd file in Photoshop to load swatches.",
                "Use the PNG overlays directly in your editor.",
            ],
        ),
        "seo_title": "Color Gradients Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "Free premium gradients for designers, editors and motion artists.",
        "published": True,
        "created_at": "2025-09-01T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/color-gradients-pack",
        "sold_count": 0,
    },
    {
        "id": str(uuid.uuid4()),
        "slug": "typography-fonts-pack",
        "name": "Typography Fonts Pack",
        "category": "Fonts",
        "price": 0,
        "sale_price": 0,
        "is_free": True,
        "description": "A free typography pack with 80+ premium fonts and title styles for video editors.",
        "features": [
            "80+ premium fonts",
            "Modern & cinematic styles",
            "Free for commercial use",
            "Easy install",
            "Works in Photoshop, AE & Premiere",
            "Lifetime updates",
        ],
        "benefits": ["Better titles", "Faster design", "Professional branding"],
        "faqs": [
            {"q": "Are these free for commercial use?", "a": "Yes, all fonts in this bundle are licensed for commercial work."},
            {"q": "How do I install them?", "a": "Double-click each font file and click \u201cInstall\u201d on Mac or Windows."},
        ],
        "images": [],
        "hero_image": "",
        "before_images": [],
        "after_images": [],
        "videos": [],
        "download_file": "https://example.com/downloads/typography-fonts-pack.zip",
        "payment_link": "",
        "landing_content": _landing(
            "Typography Fonts Pack",
            "80+ free premium fonts to design titles, lower thirds, posters and reels.",
            [
                "80+ premium fonts",
                "Modern styles",
                "Cinematic display fonts",
                "Free commercial use",
                "Cross-platform",
                "Lifetime updates",
            ],
            "Default system fonts vs. cinematic typography that feels designed.",
            _COMPAT_FONTS,
            [
                ["Price", "FREE", "\u20b9999+"],
                ["License", "Commercial OK", "Personal only"],
                ["Font count", "80+", "10\u201320"],
            ],
            [
                {"q": "Will these work on Final Cut Pro?", "a": "Yes \u2014 once installed they appear in every app."},
                {"q": "How do I install?", "a": "Double-click each .ttf/.otf and click Install."},
            ],
        ),
        "thank_you_content": _thanks(
            "Fonts unlocked!",
            "Your Typography Fonts Pack is ready.",
            [
                "Unzip the archive.",
                "Double-click each font file.",
                "Click \u201cInstall\u201d (Mac/Windows).",
                "Use the fonts in your editor of choice.",
            ],
        ),
        "seo_title": "Typography Fonts Pack \u2014 Free \u2014 PranvithDOP",
        "seo_description": "80+ free premium fonts for editors, designers and motion artists.",
        "published": True,
        "created_at": "2025-08-20T00:00:00Z",
        "updated_at": None,
        "product_url": "/assets/typography-fonts-pack",
        "sold_count": 0,
    },
]

BLOG_CATEGORIES = [
    {"id": str(uuid.uuid4()), "name": "Editing Tips", "slug": "editing-tips"},
    {"id": str(uuid.uuid4()), "name": "Workflow", "slug": "workflow"},
]

BLOG_POSTS = [
    {
        "id": str(uuid.uuid4()),
        "title": "5 Pro Editing Tricks for Premiere Pro",
        "slug": "5-pro-editing-tricks-for-premiere-pro",
        "category": "editing-tips",
        "tags": ["premiere-pro", "editing", "tips"],
        "excerpt": "Boost your Premiere Pro workflow with five pro editing tricks that save time and improve your final video.",
        "content": "Learn fast cuts, color grading shortcuts, audio cleanup, motion graphics tips, and export settings for better results.",
        "featured_image": "",
        "seo_title": "5 Pro Editing Tricks for Premiere Pro",
        "seo_description": "Discover key Premiere Pro tricks for faster workflows and better video quality.",
        "published": True,
        "created_at": "2025-11-15T00:00:00Z",
        "updated_at": None,
    },
]

SETTINGS = {
    "site_name": "PranvithDOP",
    "theme": "dark",
    "notifications_enabled": True,
    "site_description": "Premium video editing training, LUT assets, courses and editorial services.",
    "contact_email": "info@pranvithdop.com",
    "contact_phone": "+91 9059867883",
    "contact_address": "Hyderabad, India",
    "footer": {
        "brand_title": "PranvithDOP",
        "description": "Empowering creators with AI-driven tools and professional video editing resources.\nJoin the future of content creation.",
        "youtube_link": "#",
        "instagram_link": "#",
        "explore_links": [
            {"name": "Courses", "path": "/courses"},
            {"name": "About Us", "path": "/about"},
            {"name": "Our Works", "path": "/works"},
            {"name": "Assets", "path": "/assets"},
            {"name": "Privacy Policy", "path": "/privacy-policy"},
            {"name": "FAQ", "path": "/#faq"},
        ],
        "contact_location": "Hyderabad, India",
        "contact_email": "info@pranvithdop.com",
        "contact_phone": "+91 9059867883",
        "newsletter_heading": "Stay Updated",
        "newsletter_description": "Subscribe to our newsletter for the latest AI tools and editing tips.",
        "subscribe_button_text": "Subscribe",
    },
    "home_hero": {
        "badge_text": "Learn premium editing, LUTs, transitions, and storytelling workflows that get results.",
        "hero_title": "Video Editing Mastery for Creators",
        "hero_subtitle": "Master the art of video editing with our comprehensive courses. From beginner basics to advanced techniques, learn professional editing skills that transform your creative vision into stunning reality.",
        "primary_button_text": "Explore Assets",
        "primary_button_link": "/assets",
        "secondary_button_text": "Join Community",
        "secondary_button_link": "/courses",
        "hero_media_type": "auto",
        "hero_media_url": "",
        "hero_media_poster_url": "",
        "hero_media_autoplay": True,
        "hero_media_muted": True,
        "hero_media_loop": True,
    },
    "instagram_profile": {
        "username": "pranvith_dop",
        "display_name": "Pranvith Dop",
        "profile_image_url": "/assets/brand-profile.png",
        "followers_count": "5,131",
        "following_count": "10",
        "posts_count": "",
        "bio_line_1": "🎥 DOP | Filmmaker | Video Editor",
        "bio_line_2": "🚁 Drone Pilot | DI",
        "bio_line_3": "📸 Product & Commercial Photography",
        "bio_line_4": "🎨 Graphic Design",
        "link_text": "youtube.com/@pranvithdop",
        "link_url": "https://www.youtube.com/@pranvithdop",
        "follow_button_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
        "cards": [
            {"title": "Cinematic editing reel", "type": "Reel", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 0},
            {"title": "Behind the scenes", "type": "Post", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 1},
            {"title": "Drone shot preview", "type": "Video", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 2},
            {"title": "Commercial frame", "type": "Reel", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 3},
            {"title": "DI color grade", "type": "Post", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 4},
            {"title": "Graphic design post", "type": "Video", "thumbnail_image_url": "", "link_url": "https://www.instagram.com/pranvith_dop?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", "enabled": True, "sort_order": 5},
        ],
    },
}


DEFAULT_SERVICES = [
    {
        "id": str(uuid.uuid4()),
        "title": "Film DOP & Cinematography",
        "slug": "film-dop-cinematography",
        "subtitle": "Narrative visuals with deliberate framing, light, and movement.",
        "short_description": "Cinematic camera work for films, documentaries, branded stories, and visual concepts.",
        "description": "From visual planning to on-set execution, PranvithDOP shapes frames that support emotion, rhythm, and story. The focus is on cinematic lighting, camera language, movement, and clean delivery for serious productions.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Camera",
        "category": "Production",
        "offers": [
            {"title": "Visual Treatment", "description": "Shot references, mood, color direction, and camera approach for the project."},
            {"title": "On-Set Cinematography", "description": "Professional framing, lighting guidance, camera movement, and coverage planning."},
            {"title": "Delivery Support", "description": "Footage organization and post-friendly handoff for editing and grading."},
        ],
        "why_choose": [
            {"title": "Story-first images", "description": "Every frame is planned around emotion and audience attention."},
            {"title": "Cinematic discipline", "description": "Clean compositions, controlled contrast, and practical production workflows."},
            {"title": "Post-aware shooting", "description": "Footage is captured with edit, grade, and final delivery in mind."},
        ],
        "process_steps": [
            {"step": 1, "title": "Creative Brief", "description": "We understand the story, references, scale, and delivery goals."},
            {"step": 2, "title": "Visual Planning", "description": "We shape shot lists, mood, camera style, and shoot priorities."},
            {"step": 3, "title": "Shoot Execution", "description": "We capture cinematic coverage with attention to light, movement, and continuity."},
            {"step": 4, "title": "Handoff", "description": "We organize footage and support post-production delivery."},
        ],
        "cta_title": "Ready to build a cinematic visual language?",
        "cta_button_text": "Contact PranvithDOP",
        "cta_button_url": "/hire",
        "sort_order": 1,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Wedding Cinematography",
        "slug": "wedding-cinematography",
        "subtitle": "Emotional wedding films with cinematic rhythm and real moments.",
        "short_description": "Premium wedding cinematography, highlight films, reels, drone coverage, and story-led edits.",
        "description": "Wedding films should feel personal, elegant, and alive. We capture the atmosphere, rituals, people, and quiet moments with a cinematic approach that keeps the memory honest.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Heart",
        "category": "Weddings",
        "offers": [
            {"title": "Wedding Films", "description": "Cinematic highlight and full-length films shaped around the real emotion of the day."},
            {"title": "Reels & Teasers", "description": "Short-form edits for Instagram, YouTube Shorts, and family sharing."},
            {"title": "Drone Coverage", "description": "Aerial visuals for venue, arrival, and atmosphere when location permissions allow."},
        ],
        "why_choose": [
            {"title": "Emotion without clutter", "description": "Films are elegant, paced, and focused on moments that matter."},
            {"title": "Cinematic coverage", "description": "Light, movement, details, and sound are handled with care."},
            {"title": "Modern delivery", "description": "Wedding content is prepared for families and social platforms."},
        ],
        "process_steps": [
            {"step": 1, "title": "Event Planning", "description": "We discuss dates, rituals, venues, schedule, and must-capture moments."},
            {"step": 2, "title": "Shoot", "description": "We cover the event with cinematic compositions and natural storytelling."},
            {"step": 3, "title": "Edit", "description": "We build the film with music, sound, color, and emotional pacing."},
            {"step": 4, "title": "Delivery", "description": "You receive final films and social-ready versions."},
        ],
        "cta_title": "Make your wedding film feel timeless.",
        "cta_button_text": "Check Availability",
        "cta_button_url": "/hire",
        "sort_order": 2,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Commercial Ad Films",
        "slug": "commercial-ad-films",
        "subtitle": "Brand films, product ads, and campaign videos built for attention.",
        "short_description": "High-impact commercial videos for brands, products, launches, and digital campaigns.",
        "description": "Commercial content needs clarity, polish, and momentum. We create ad films that communicate value quickly while keeping the visuals premium and platform-ready.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Clapperboard",
        "category": "Commercial",
        "offers": [
            {"title": "Brand Films", "description": "Story-led videos for brand identity, launches, and campaigns."},
            {"title": "Product Videos", "description": "Clean visuals, close-ups, motion, and edits that make products feel desirable."},
            {"title": "Social Ad Cuts", "description": "Multiple aspect ratios and short edits for ads and organic content."},
        ],
        "why_choose": [
            {"title": "Conversion-aware storytelling", "description": "Visuals are shaped to hold attention and support action."},
            {"title": "Premium production value", "description": "Cinematic camera, lighting, edit, and grade in one workflow."},
            {"title": "Platform-ready output", "description": "Deliverables are prepared for Instagram, YouTube, websites, and ads."},
        ],
        "process_steps": [
            {"step": 1, "title": "Brief", "description": "We identify product, audience, message, and campaign goal."},
            {"step": 2, "title": "Concept", "description": "We plan hooks, scenes, references, and deliverable formats."},
            {"step": 3, "title": "Production", "description": "We shoot with controlled visuals and clean campaign coverage."},
            {"step": 4, "title": "Post", "description": "We edit, grade, sound-design, and export versions for each platform."},
        ],
        "cta_title": "Launch with a commercial that looks premium.",
        "cta_button_text": "Plan My Ad Film",
        "cta_button_url": "/hire",
        "sort_order": 3,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Drone Cinematography",
        "slug": "drone-cinematography",
        "subtitle": "Aerial visuals for scale, atmosphere, and cinematic transitions.",
        "short_description": "Drone footage for weddings, real estate, brand films, events, travel, and location showcases.",
        "description": "Aerial shots can instantly add scale and production value. We capture smooth, purposeful drone visuals that support the edit instead of feeling like filler.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Plane",
        "category": "Aerial",
        "offers": [
            {"title": "Establishing Shots", "description": "Venue, landscape, property, and city visuals with cinematic movement."},
            {"title": "Event Coverage", "description": "Aerial moments for weddings, launches, outdoor events, and gatherings."},
            {"title": "Brand & Real Estate", "description": "Aerial content for campaigns, properties, resorts, and travel showcases."},
        ],
        "why_choose": [
            {"title": "Purposeful movement", "description": "Shots are designed to serve the story and edit rhythm."},
            {"title": "Clean visual control", "description": "Smooth flight paths, exposure care, and cinematic framing."},
            {"title": "Permission-aware planning", "description": "We discuss feasibility, location constraints, and safety before the shoot."},
        ],
        "process_steps": [
            {"step": 1, "title": "Location Check", "description": "We review location, timing, permissions, and weather."},
            {"step": 2, "title": "Shot Plan", "description": "We define movement, altitude, subjects, and transitions."},
            {"step": 3, "title": "Flight", "description": "We capture steady, cinematic aerial footage."},
            {"step": 4, "title": "Delivery", "description": "We deliver organized clips or edited aerial sequences."},
        ],
        "cta_title": "Add scale to your next story.",
        "cta_button_text": "Book Drone Shoot",
        "cta_button_url": "/hire",
        "sort_order": 4,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Music Videos",
        "slug": "music-videos",
        "subtitle": "Performance, mood, movement, and edit energy for artists.",
        "short_description": "Concept-driven music videos, performance shoots, creative edits, and color-driven visuals.",
        "description": "Music videos need a visual identity that matches the track. We build scenes, movement, cuts, and color around the sound so the final video feels intentional and replayable.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Music",
        "category": "Music",
        "offers": [
            {"title": "Concept Videos", "description": "Moodboards, visual ideas, and scene planning around the track."},
            {"title": "Performance Shoots", "description": "Camera movement and coverage for artists, bands, and dancers."},
            {"title": "Stylized Edits", "description": "Beat cuts, effects, color, and pacing designed for repeat viewing."},
        ],
        "why_choose": [
            {"title": "Track-led rhythm", "description": "The edit responds to beat, emotion, and artist identity."},
            {"title": "Strong visual mood", "description": "Color, light, and frames are designed around the song world."},
            {"title": "Social-ready versions", "description": "Short cuts can be delivered for reels and promotional drops."},
        ],
        "process_steps": [
            {"step": 1, "title": "Song Study", "description": "We identify mood, references, locations, and performance style."},
            {"step": 2, "title": "Pre-Production", "description": "We prepare shot ideas, props, looks, and schedule."},
            {"step": 3, "title": "Shoot", "description": "We capture performance and visual scenes with energy."},
            {"step": 4, "title": "Edit & Grade", "description": "We shape rhythm, effects, color, and final delivery."},
        ],
        "cta_title": "Give your track a visual world.",
        "cta_button_text": "Start Music Video",
        "cta_button_url": "/hire",
        "sort_order": 5,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Video Editing",
        "slug": "video-editing",
        "subtitle": "Clean, cinematic edits for brands, weddings, creators, and campaigns.",
        "short_description": "Professional editing, story structure, sound design, pacing, captions, and exports.",
        "description": "Editing is where footage becomes a story. We refine structure, rhythm, sound, color direction, and platform delivery so your video feels polished and purposeful.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Scissors",
        "category": "Post Production",
        "offers": [
            {"title": "Story Edits", "description": "Narrative structure, pacing, selects, and emotional flow."},
            {"title": "Social Edits", "description": "Reels, shorts, captions, hooks, and platform-specific exports."},
            {"title": "Sound & Polish", "description": "Music, transitions, sound design, cleanup, and final delivery."},
        ],
        "why_choose": [
            {"title": "Strong storytelling", "description": "Footage is shaped around clarity and emotional momentum."},
            {"title": "Cinematic finish", "description": "Sound, transitions, and pacing are treated with care."},
            {"title": "Reliable workflow", "description": "Feedback rounds and deliveries are organized clearly."},
        ],
        "process_steps": [
            {"step": 1, "title": "Footage Review", "description": "We collect files, brief, references, and delivery requirements."},
            {"step": 2, "title": "First Cut", "description": "We create the structure and pacing for review."},
            {"step": 3, "title": "Refine", "description": "We handle feedback, sound, graphics, and polish."},
            {"step": 4, "title": "Export", "description": "We deliver final versions for each platform."},
        ],
        "cta_title": "Turn raw footage into a polished film.",
        "cta_button_text": "Send Footage Brief",
        "cta_button_url": "/hire",
        "sort_order": 6,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Color Grading",
        "slug": "color-grading",
        "subtitle": "Cinematic color, contrast, skin tones, and final look development.",
        "short_description": "Professional color correction and grading for films, weddings, ads, reels, and music videos.",
        "description": "Color grading gives footage its final emotion. We balance exposure, contrast, skin tones, and creative look so the project feels cohesive and cinematic.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Palette",
        "category": "Post Production",
        "offers": [
            {"title": "Color Correction", "description": "Balance exposure, white balance, contrast, and shot matching."},
            {"title": "Look Development", "description": "Create cinematic palettes and mood-specific color styles."},
            {"title": "Final Delivery", "description": "Exports prepared for web, social, and client review."},
        ],
        "why_choose": [
            {"title": "Natural skin tones", "description": "Looks are polished without sacrificing people and emotion."},
            {"title": "Cohesive mood", "description": "Scenes are matched into one consistent visual language."},
            {"title": "Cinematic restraint", "description": "Color supports the story instead of overpowering it."},
        ],
        "process_steps": [
            {"step": 1, "title": "Reference", "description": "We define mood, contrast, saturation, and delivery target."},
            {"step": 2, "title": "Balance", "description": "We correct exposure, color temperature, and shot consistency."},
            {"step": 3, "title": "Grade", "description": "We apply the creative look and refine key scenes."},
            {"step": 4, "title": "Master", "description": "We export final graded versions."},
        ],
        "cta_title": "Give your footage the final cinematic finish.",
        "cta_button_text": "Grade My Project",
        "cta_button_url": "/hire",
        "sort_order": 7,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Instagram / YouTube Content",
        "slug": "instagram-youtube-content",
        "subtitle": "Short-form and creator content engineered for retention.",
        "short_description": "Reels, shorts, thumbnails, captions, hooks, edits, and content packages for creators and brands.",
        "description": "Platform content needs speed, clarity, and repeatable quality. We create edits that open strong, move fast, and stay aligned with your visual identity.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "PlaySquare",
        "category": "Social Content",
        "offers": [
            {"title": "Reels & Shorts", "description": "Fast-paced vertical edits with hooks, captions, music, and polish."},
            {"title": "YouTube Edits", "description": "Talking-head, vlog, tutorial, and brand videos with clear pacing."},
            {"title": "Content Packages", "description": "Batch edits for campaigns, creators, and monthly content calendars."},
        ],
        "why_choose": [
            {"title": "Retention-focused pacing", "description": "Cuts are designed to hold attention without feeling messy."},
            {"title": "Creator-friendly workflow", "description": "Repeatable formats, clean feedback, and platform exports."},
            {"title": "Premium visual identity", "description": "Your content feels consistent and brand-ready."},
        ],
        "process_steps": [
            {"step": 1, "title": "Content Goal", "description": "We define audience, platform, length, and style."},
            {"step": 2, "title": "Edit Batch", "description": "We create first cuts with hooks, captions, and pacing."},
            {"step": 3, "title": "Review", "description": "We refine based on feedback and platform needs."},
            {"step": 4, "title": "Deliver", "description": "We export final versions in required formats."},
        ],
        "cta_title": "Build content that feels sharp and consistent.",
        "cta_button_text": "Create Content Plan",
        "cta_button_url": "/hire",
        "sort_order": 8,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Website Design & Development",
        "slug": "website-design-development",
        "subtitle": "Modern websites for creators, studios, brands, and service businesses.",
        "short_description": "Premium website design and development with cinematic presentation, clear structure, and fast delivery.",
        "description": "A good website should make your work easy to understand and easy to trust. We design and build polished web experiences for creators, studios, brands, and businesses.",
        "banner_url": "",
        "thumbnail_url": "",
        "icon": "Globe",
        "category": "Web",
        "offers": [
            {"title": "Website Design", "description": "Visual layouts, content structure, and responsive page design."},
            {"title": "Development", "description": "Modern frontend builds, CMS-ready structures, and deployment support."},
            {"title": "Service Pages", "description": "Landing pages and detail pages that explain offers clearly."},
        ],
        "why_choose": [
            {"title": "Creator-aware design", "description": "Sites are shaped for portfolios, service enquiries, and digital products."},
            {"title": "Premium visual feel", "description": "Dark, cinematic, polished interfaces with practical UX."},
            {"title": "Business-ready structure", "description": "Clear navigation, CTAs, and responsive layouts."},
        ],
        "process_steps": [
            {"step": 1, "title": "Discovery", "description": "We define goals, pages, content, references, and audience."},
            {"step": 2, "title": "Design", "description": "We create the layout and visual direction."},
            {"step": 3, "title": "Build", "description": "We develop responsive pages and connect required systems."},
            {"step": 4, "title": "Launch", "description": "We test, deploy, and hand off the site."},
        ],
        "cta_title": "Need a site that presents your work beautifully?",
        "cta_button_text": "Discuss Website",
        "cta_button_url": "/hire",
        "sort_order": 9,
        "is_published": True,
        "created_at": "2026-06-25T00:00:00Z",
        "updated_at": None,
    },
]

