import React, { useEffect, useState } from 'react';
import { Download, FileSpreadsheet, Printer, RefreshCw } from 'lucide-react';
import { adminApi, fetchAdminReport } from '../../lib/api';

const ranges = { Today: 0, Yesterday: 1, 'Last 7 Days': 6, 'This Month': 30, 'This Year': 365 };
const Reports = () => {
  const [tab, setTab] = useState('orders'); const [range, setRange] = useState('Last 7 Days'); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [data, setData] = useState({ items: [], summary: {} }); const [dashboard, setDashboard] = useState({});
  const params = () => { const days = ranges[range]; const end = new Date(); const start = new Date(); start.setDate(end.getDate() - days); if (range === 'Yesterday') { end.setDate(end.getDate() - 1); } return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10), search, status_filter: status }; };
  const load = async () => { setData(await fetchAdminReport(tab, params())); setDashboard(await fetchAdminReport('dashboard')); };
  // Keep search manual: changing the search box should not reload until Enter or refresh.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load().catch(() => setData({ items: [], summary: {} })); }, [tab, range, status]);
  const exportFile = async (format) => { const res = await adminApi.get(`/admin/reports/export/${format}`, { params: params(), responseType: 'blob' }); const a = document.createElement('a'); a.href = URL.createObjectURL(res.data); a.download = `report.${format === 'excel' ? 'xlsx' : format}`; a.click(); URL.revokeObjectURL(a.href); };
  const cards = [['Today’s Orders', dashboard.today_orders], ['Today’s Revenue', `₹${((dashboard.today_revenue || 0) / 100).toLocaleString()}`], ['Lifetime Revenue', `₹${((dashboard.lifetime_revenue || 0) / 100).toLocaleString()}`], ['Customers', dashboard.total_customers], ['Downloads', dashboard.total_downloads], ['Pending', dashboard.pending_orders]];
  const rows = data.items || [];
  return <div className="space-y-6 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-semibold">Reports & Analytics</h1><p className="mt-1 text-sm text-slate-400">Orders, customers, downloads and revenue insights.</p></div><div className="flex gap-2"><button onClick={() => exportFile('excel')} className="btn-primary"><FileSpreadsheet size={16}/> Excel</button><button onClick={() => exportFile('csv')} className="btn-secondary"><Download size={16}/> CSV</button><button onClick={() => exportFile('pdf')} className="btn-secondary">PDF</button><button onClick={() => window.print()} className="btn-secondary"><Printer size={16}/> Print</button></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value ?? 0}</p></div>)}</div><div className="flex flex-wrap gap-2">{['orders','customers','downloads','revenue','products'].map(x => <button key={x} onClick={() => setTab(x)} className={tab === x ? 'btn-primary' : 'btn-secondary'}>{x}</button>)}<select value={range} onChange={e => setRange(e.target.value)} className="rounded-xl bg-white/10 px-3">{Object.keys(ranges).map(x => <option key={x}>{x}</option>)}</select>{tab === 'orders' && <><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} placeholder="Search order, email, product…" className="rounded-xl bg-white/10 px-3"/><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl bg-white/10 px-3">{['all','paid','pending','failed','cancelled'].map(x => <option key={x}>{x}</option>)}</select><button onClick={load} className="btn-secondary"><RefreshCw size={16}/></button></>}</div><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-sm"><thead className="bg-white/[.06]"><tr>{Object.keys(rows[0] || {}).filter(x => x !== '_id').slice(0, 12).map(k => <th className="whitespace-nowrap px-3 py-3 text-left" key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i) => <tr className="border-t border-white/5" key={row.id || row.email || i}>{Object.keys(rows[0] || {}).filter(x => x !== '_id').slice(0,12).map(k => <td className="max-w-48 truncate px-3 py-3 text-slate-300" key={k}>{Array.isArray(row[k]) ? row[k].join(', ') : String(row[k] ?? '')}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center text-slate-400">No report data for this range.</p>}</div></div>;
};
export default Reports;
