import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Download, LogIn, Search, ShieldCheck } from 'lucide-react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { customerDownloadLink, fetchCustomerDashboard, fetchCustomerOrder, fetchCustomerOrders, requestCustomerOtp, setCustomerAuthToken, verifyCustomerOtp } from '../lib/api';

const money = (amount = 0) => `₹${(Number(amount) / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
const download = async (id) => { const { url } = await customerDownloadLink(id); window.location.assign(url); };

export default function Account() {
  const { orderId } = useParams(); const navigate = useNavigate();
  const [token, setToken] = useState(() => localStorage.getItem('customer_access_token') || '');
  const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState('');
  const [dashboard, setDashboard] = useState(null); const [orders, setOrders] = useState([]); const [search, setSearch] = useState(''); const [order, setOrder] = useState(null);
  useEffect(() => { if (!token) return; setCustomerAuthToken(token); Promise.all([fetchCustomerDashboard(), fetchCustomerOrders({ search })]).then(([d, o]) => { setDashboard(d); setOrders(o.items); }).catch(e => { setError(e?.response?.data?.detail || 'Could not load your account'); }); }, [token, search]);
  useEffect(() => { if (token && orderId) fetchCustomerOrder(orderId).then(setOrder).catch(e => setError(e?.response?.data?.detail || 'Order not found')); }, [token, orderId]);
  const signIn = async (e) => { e.preventDefault(); setError(''); try { if (!sent) { await requestCustomerOtp(email); setSent(true); return; } const r = await verifyCustomerOtp(email, code); localStorage.setItem('customer_access_token', r.access_token); setCustomerAuthToken(r.access_token); setToken(r.access_token); } catch (x) { setError(x?.response?.data?.detail || 'Unable to sign in'); } };
  if (!token) return <main className="page min-h-screen bg-[var(--bg-main)] text-white"><Header /><section className="mx-auto max-w-md px-6 pb-24 pt-32"><div className="rounded-3xl border border-white/10 bg-[var(--bg-card)] p-7"><ShieldCheck className="text-violet-300" /><h1 className="mt-4 text-3xl font-black">My Account</h1><p className="mt-2 text-sm text-white/60">Access purchases immediately—no password and no waiting for email.</p><form onSubmit={signIn} className="mt-6 space-y-3"><input className="w-full rounded-xl border border-white/15 bg-black/20 p-3" type="email" required placeholder="Email used at checkout" value={email} onChange={e=>setEmail(e.target.value)} />{sent && <input className="w-full rounded-xl border border-white/15 bg-black/20 p-3" inputMode="numeric" required placeholder="6-digit code" value={code} onChange={e=>setCode(e.target.value)} />}{error && <p className="text-sm text-rose-300">{error}</p>}<button className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 p-3 font-semibold"><LogIn size={17}/>{sent ? 'Verify and continue' : 'Email me a sign-in code'}</button></form></div></section><Footer /></main>;
  const selected = order || (orderId ? null : undefined);
  return <main className="page min-h-screen bg-[var(--bg-main)] text-white"><Header /><section className="mx-auto max-w-6xl px-5 pb-24 pt-28"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-violet-300">Customer account</p><h1 className="mt-2 text-3xl font-black">{selected ? 'Payment Successful' : 'My downloads'}</h1><p className="mt-2 text-white/60">Email confirmation is being prepared. Your files are ready now.</p></div><Link to="/assets" className="rounded-full border border-white/15 px-5 py-3 text-sm">Continue shopping</Link></div>{error && <p className="mt-5 text-rose-300">{error}</p>}{selected && <OrderCard order={selected} primary onDownload={()=>download(selected.id)} />}{!selected && <><div className="mt-8 grid grid-cols-3 gap-3">{[['Purchased assets',dashboard?.purchased_assets],['Total orders',dashboard?.total_orders],['Downloads',dashboard?.total_downloads]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-2xl font-black">{v ?? '—'}</p><p className="text-xs text-white/55">{l}</p></div>)}</div><div className="mt-8 flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-3"><Search size={16} className="text-white/45"/><input className="w-full bg-transparent py-3 outline-none" placeholder="Search orders" value={search} onChange={e=>setSearch(e.target.value)} /></div><div className="mt-4 space-y-3">{orders.map(o=><OrderCard key={o.id} order={o} onDownload={()=>download(o.id)} />)}{!orders.length && <p className="py-10 text-center text-white/50">No verified paid orders yet.</p>}</div></>}</section><Footer /></main>;
}
function OrderCard({ order, onDownload, primary }) { return <article className={`mt-8 rounded-2xl border border-white/10 bg-[var(--bg-card)] p-5 ${primary?'':'mt-0'}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-bold">{order.product_name}</p><p className="mt-1 text-sm text-white/55">{new Date(order.paid_at || order.created_at).toLocaleDateString()} · {money(order.amount)} · <span className="text-emerald-300">Paid</span></p><p className="mt-2 text-xs text-white/45">Downloaded {order.download_count || 0} times {order.last_downloaded_at ? `· Last download ${new Date(order.last_downloaded_at).toLocaleDateString()}` : ''}</p></div><button onClick={onDownload} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-violet-600 px-6 font-semibold"><Download size={17}/>Download now</button></div></article>}
